```mermaid
graph TD
    root["🚀 Alpha Project Root"]
    root --> dir_1["📂 Config/"]
    root --> dir_2["📂 Containers/"]
    root --> dir_3["📂 LogsPersonalizados/"]
    root --> dir_4["📂 core/"]
    dir_4 --> dir_5["📂 Admin/"]
    dir_5 --> dir_6["📂 Controllers/"]
    dir_6 --> dir_7["📂 Actions/"]
    dir_7 --> dir_8["📂 Auth/"]
    dir_7 --> dir_9["📂 Catalog/"]
    dir_9 --> dir_10["📂 Category/"]
    dir_9 --> dir_11["📂 Product/"]
    dir_7 --> dir_12["📂 Dashboard/"]
    dir_7 --> dir_13["📂 Sales/"]
    dir_13 --> dir_14["📂 Order/"]
    dir_13 --> dir_15["📂 Voucher/"]
    dir_5 --> dir_16["📂 Repositories/"]
    dir_4 --> dir_17["📂 Auth/"]
    dir_17 --> dir_18["📂 Middleware/"]
    dir_17 --> dir_19["📂 Services/"]
    dir_4 --> dir_20["📂 Controller/"]
    dir_20 --> dir_21["📂 Actions/"]
    dir_21 --> dir_22["📂 Cart/"]
    dir_21 --> dir_23["📂 Category/"]
    dir_21 --> dir_24["📂 Customer/"]
    dir_24 --> dir_25["📂 Account/"]
    dir_24 --> dir_26["📂 Addresses/"]
    dir_24 --> dir_27["📂 Auth/"]
    dir_21 --> dir_28["📂 Information/"]
    dir_21 --> dir_29["📂 Location/"]
    dir_21 --> dir_30["📂 Main/"]
    dir_21 --> dir_31["📂 Product/"]
    dir_20 --> dir_32["📂 Api/"]
    dir_20 --> dir_33["📂 Auth/"]
    dir_20 --> dir_34["📂 Web/"]
    dir_4 --> dir_35["📂 Mappers/"]
    dir_35 --> dir_36["📂 EntityMappers/"]
    dir_35 --> dir_37["📂 Observers/"]
    dir_4 --> dir_38["📂 Model/"]
    dir_38 --> dir_39["📂 DataAccessObject/"]
    dir_38 --> dir_40["📂 DataTransferObject/"]
    dir_40 --> dir_41["📂 Attributes/"]
    dir_38 --> dir_42["📂 Domain/"]
    dir_42 --> dir_43["📂 Attributes/"]
    dir_42 --> dir_44["📂 DTOs/"]
    dir_42 --> dir_45["📂 Entities/"]
    dir_45 --> dir_46["📂 Customer/"]
    dir_45 --> dir_47["📂 Geo/"]
    dir_45 --> dir_48["📂 Supplier/"]
    dir_42 --> dir_49["📂 Factory/"]
    dir_42 --> dir_50["📂 Observers/"]
    dir_42 --> dir_51["📂 Repositories/"]
    dir_4 --> dir_52["📂 Services/"]
    dir_52 --> dir_53["📂 Menu/"]
    dir_52 --> dir_54["📂 Shipping/"]
    dir_4 --> dir_55["📂 Session/"]
    dir_4 --> dir_56["📂 Support/"]
    dir_56 --> dir_57["📂 Cache/"]
    dir_56 --> dir_58["📂 Presenters/"]
    dir_56 --> dir_59["📂 Twig/"]
    dir_4 --> dir_60["📂 View/"]
    dir_60 --> dir_61["📂 Errors/"]
    dir_4 --> dir_62["📂 language/"]
    dir_62 --> dir_63["📂 en-gb/"]
    dir_63 --> dir_64["📂 account/"]
    dir_63 --> dir_65["📂 api/"]
    dir_63 --> dir_66["📂 checkout/"]
    dir_63 --> dir_67["📂 cms/"]
    dir_63 --> dir_68["📂 common/"]
    dir_63 --> dir_69["📂 cron/"]
    dir_63 --> dir_70["📂 error/"]
    dir_63 --> dir_71["📂 information/"]
    dir_63 --> dir_72["📂 mail/"]
    dir_63 --> dir_73["📂 product/"]
    dir_63 --> dir_74["📂 tool/"]
    dir_62 --> dir_75["📂 fr-fr/"]
    dir_75 --> dir_76["📂 account/"]
    dir_75 --> dir_77["📂 api/"]
    dir_75 --> dir_78["📂 checkout/"]
    dir_75 --> dir_79["📂 cms/"]
    dir_75 --> dir_80["📂 common/"]
    dir_75 --> dir_81["📂 cron/"]
    dir_75 --> dir_82["📂 error/"]
    dir_75 --> dir_83["📂 information/"]
    dir_75 --> dir_84["📂 mail/"]
    dir_75 --> dir_85["📂 product/"]
    dir_75 --> dir_86["📂 tool/"]
    dir_62 --> dir_87["📂 pt-br/"]
    dir_87 --> dir_88["📂 account/"]
    dir_87 --> dir_89["📂 affiliate/"]
    dir_87 --> dir_90["📂 api/"]
    dir_87 --> dir_91["📂 checkout/"]
    dir_87 --> dir_92["📂 common/"]
    dir_87 --> dir_93["📂 error/"]
    dir_87 --> dir_94["📂 extension/"]
    dir_94 --> dir_95["📂 captcha/"]
    dir_94 --> dir_96["📂 credit_card/"]
    dir_94 --> dir_97["📂 module/"]
    dir_94 --> dir_98["📂 openbay/"]
    dir_94 --> dir_99["📂 payment/"]
    dir_94 --> dir_100["📂 recurring/"]
    dir_94 --> dir_101["📂 shipping/"]
    dir_94 --> dir_102["📂 total/"]
    dir_87 --> dir_103["📂 information/"]
    dir_87 --> dir_104["📂 mail/"]
    dir_87 --> dir_105["📂 product/"]
    dir_87 --> dir_106["📂 tool/"]
    root --> dir_107["📂 data_base_new_schema/"]
    root --> dir_108["📂 diagrams/"]
    root --> dir_109["📂 docs/"]
    root --> dir_110["📂 lib/"]
    root --> dir_111["📂 public_html/"]
    dir_111 --> dir_112["📂 LPDHED2dC7Gjrg2b/"]
    dir_111 --> dir_113["📂 css/"]
    dir_113 --> dir_114["📂 admin/"]
    dir_113 --> dir_115["📂 assets/"]
    dir_115 --> dir_116["📂 css/"]
    dir_113 --> dir_117["📂 custom/"]
    dir_111 --> dir_118["📂 fonts/"]
    dir_118 --> dir_119["📂 fontawesome/"]
    dir_119 --> dir_120["📂 css/"]
    dir_119 --> dir_121["📂 webfonts/"]
    dir_111 --> dir_122["📂 img/"]
    dir_122 --> dir_123["📂 banners/"]
    dir_122 --> dir_124["📂 manufacturer/"]
    dir_122 --> dir_125["📂 product/"]
    dir_125 --> dir_126["📂 cimento_liz/"]
    dir_125 --> dir_127["📂 votoran/"]
    dir_122 --> dir_128["📂 seamless/"]
    dir_111 --> dir_129["📂 js/"]
    dir_129 --> dir_130["📂 cart/"]
    dir_129 --> dir_131["📂 custom/"]
    dir_111 --> dir_132["📂 mockup-navegavel/"]
    dir_132 --> dir_133["📂 mockup2/"]
    dir_133 --> dir_134["📂 carrinho_arquivos/"]
    dir_133 --> dir_135["📂 categoria_arquivos/"]
    dir_133 --> dir_136["📂 checkout2_arquivos/"]
    dir_133 --> dir_137["📂 checkout3_arquivos/"]
    dir_133 --> dir_138["📂 checkout_arquivos/"]
    dir_133 --> dir_139["📂 editar-endereco_arquivos/"]
    dir_133 --> dir_140["📂 enderecos_arquivos/"]
    dir_133 --> dir_141["📂 index_arquivos/"]
    dir_133 --> dir_142["📂 minha-conta_arquivos/"]
    dir_133 --> dir_143["📂 novo-endereco_arquivos/"]
    dir_133 --> dir_144["📂 pedido-14_arquivos/"]
    dir_133 --> dir_145["📂 pedidos_arquivos/"]
    dir_133 --> dir_146["📂 produto_arquivos/"]
    dir_133 --> dir_147["📂 sucesso_arquivos/"]
    root --> dir_148["📂 resources/"]
    dir_148 --> dir_149["📂 views/"]
    dir_149 --> dir_150["📂 admin/"]
    dir_150 --> dir_151["📂 auth/"]
    dir_150 --> dir_152["📂 components/"]
    dir_152 --> dir_153["📂 organisms/"]
    dir_150 --> dir_154["📂 layouts/"]
    dir_150 --> dir_155["📂 pages/"]
    dir_155 --> dir_156["📂 dashboard/"]
    dir_149 --> dir_157["📂 components/"]
    dir_157 --> dir_158["📂 atoms/"]
    dir_157 --> dir_159["📂 molecules/"]
    dir_157 --> dir_160["📂 organisms/"]
    dir_149 --> dir_161["📂 layouts/"]
    dir_149 --> dir_162["📂 pages/"]
    dir_162 --> dir_163["📂 cart/"]
    dir_162 --> dir_164["📂 category/"]
    dir_162 --> dir_165["📂 errors/"]
    dir_162 --> dir_166["📂 information/"]
    dir_162 --> dir_167["📂 product/"]
    dir_162 --> dir_168["📂 users/"]
    dir_168 --> dir_169["📂 accounts/"]
    dir_168 --> dir_170["📂 addresses/"]
    root --> dir_171["📂 tests/"]
    dir_171 --> dir_172["📂 scripts_uteis/"]
    dir_172 --> dir_173["📂 NovoEnderecamento/"]
```
