INSERT INTO `agsc_zones`(`iso_code`, `country_id`, `name`) -- Script SQL para Inserção de todos os Condados da Suécia
VALUES ('SE-AB', 752, 'Stockholm'),
    -- Se já inseriu anteriormente, o MySQL apenas ignorará ou dará aviso de duplicidade
    ('SE-C', 752, 'Uppsala'),
    ('SE-D', 752, 'Södermanland'),
    ('SE-E', 752, 'Östergötland'),
    ('SE-F', 752, 'Jönköping'),
    ('SE-G', 752, 'Kronoberg'),
    ('SE-H', 752, 'Kalmar'),
    ('SE-I', 752, 'Gotland'),
    ('SE-K', 752, 'Blekinge'),
    ('SE-M', 752, 'Skåne'),
    ('SE-N', 752, 'Halland'),
    ('SE-O', 752, 'Västra Götaland'),
    ('SE-S', 752, 'Värmland'),
    ('SE-T', 752, 'Örebro'),
    ('SE-U', 752, 'Västmanland'),
    ('SE-W', 752, 'Dalarna'),
    ('SE-X', 752, 'Gävleborg'),
    ('SE-Y', 752, 'Västernorrland'),
    ('SE-Z', 752, 'Jämtland'),
    ('SE-AC', 752, 'Västerbotten'),
    ('SE-BD', 752, 'Norrbotten');