INSERT IGNORE INTO `agsc_zones`(`iso_code`, `country_id`, `name`)
VALUES -- Script SQL para Inserção de todos os Estados Brasileiros
    ('BR-AC', 76, 'Acre'),
    ('BR-AL', 76, 'Alagoas'),
    ('BR-AM', 76, 'Amazonas'),
    ('BR-AP', 76, 'Amapá'),
    ('BR-BA', 76, 'Bahia'),
    ('BR-CE', 76, 'Ceará'),
    ('BR-DF', 76, 'Distrito Federal'),
    ('BR-ES', 76, 'Espírito Santo'),
    ('BR-GO', 76, 'Goiás'),
    ('BR-MA', 76, 'Maranhão'),
    ('BR-MG', 76, 'Minas Gerais'),
    ('BR-MS', 76, 'Mato Grosso do Sul'),
    ('BR-MT', 76, 'Mato Grosso'),
    ('BR-PA', 76, 'Pará'),
    ('BR-PB', 76, 'Paraíba'),
    ('BR-PE', 76, 'Pernambuco'),
    ('BR-PI', 76, 'Piauí'),
    ('BR-PR', 76, 'Paraná'),
    ('BR-RJ', 76, 'Rio de Janeiro'),
    ('BR-RN', 76, 'Rio Grande do Norte'),
    ('BR-RO', 76, 'Rondônia'),
    ('BR-RR', 76, 'Roraima'),
    ('BR-RS', 76, 'Rio Grande do Sul'),
    ('BR-SC', 76, 'Santa Catarina'),
    ('BR-SE', 76, 'Sergipe'),
    ('BR-SP', 76, 'São Paulo'),
    -- Se já inseriu anteriormente, o MySQL apenas ignorará ou dará aviso de duplicidade dependendo da sua configuração
    ('BR-TO', 76, 'Tocantins');