classDiagram
    class Customer {
        -string email
        -string firstname
        -string lastname
        -bool status
        +getAddresses() Collection
        +getCustomerGroup() CustomerGroup
    }

    class Address {
        -string address1
        -string city
        -string postcode
    }

    class CustomerGroup {
        -bool approval
    }

    class Country {
        -string name
        -string isoCode2
    }

    class Zone {
        -string name
        -string code
    }

    Customer "1" *-- "many" Address : OneToMany (LAZY)
    Address "many" o-- "1" Country : ManyToOne
    Address "many" o-- "1" Zone : ManyToOne

    note for Customer "Raiz de Agregado: Centraliza a<br>identidade e autenticação.<br> Gerencia a coleção de endereços e<br> o perfil de acesso."
    note for Address "Multi-endereçamento: Permite múltiplos locais<br>de entrega/faturamento. O uso de LAZY<br> garante que<br> o login seja rápido, carregando detalhes apenas no checkout."
    note for CustomerGroup "Políticas de Grupo: Define se o cliente<br> precisa de aprovação, quais<br> descontos visualiza e<br> as regras fiscais aplicáveis (B2B vs B2C)."
    note for Customer "Relacionamentos: Atributos #[ManyToOne] e #[OneToMany]<br> orientam o DAO sobre como resolver<br> chaves estrangeiras e carregar<br> coleções automaticamente."