```mermaid
graph TD
    root["🚀 Alpha Project Root"]
    root --> node_1("📄 .antigravityrc")
    root --> node_2("📄 .gitignore")
    root --> node_3("📄 20240528_105000.md")
    root --> node_4["📂 Config/"]
    node_4 --> node_5("📄 Routes.php")
    root --> node_6["📂 Containers/"]
    node_6 --> node_7("📄 AppBootstrap.php")
    node_6 --> node_8("📄 AppContainer.php")
    node_6 --> node_9("📄 nota_20241103_165000.md")
    node_6 --> node_10("📄 nota_20241103_170000.md")
    node_6 --> node_11("📄 nota_20241103_171000.md")
    root --> node_12["📂 LogsPersonalizados/"]
    node_12 --> node_13("📄 Log.php")
    root --> node_14("📄 PaymentGatewayFactory.php")
    root --> node_15("📄 PaymentGatewayInterface.php")
    root --> node_16("📄 PaymentResult.php")
    root --> node_17("📄 ProcessPaymentAction.php")
    root --> node_18("📄 README.md")
    root --> node_19("📄 composer.json")
    root --> node_20("📄 config.php")
    root --> node_21["📂 core/"]
    node_21 --> node_22["📂 Admin/"]
    node_22 --> node_23["📂 Controllers/"]
    node_23 --> node_24["📂 Actions/"]
    node_24 --> node_25["📂 Auth/"]
    node_25 --> node_26("📄 LoginAction.php")
    node_25 --> node_27("📄 LogoutAction.php")
    node_25 --> node_28("📄 ResetPasswordAction.php")
    node_25 --> node_29("📄 ShowLoginAction.php")
    node_24 --> node_30["📂 Catalog/"]
    node_30 --> node_31["📂 Category/"]
    node_31 --> node_32("📄 CreateCategoryAction.php")
    node_31 --> node_33("📄 ListCategoriesAction.php")
    node_31 --> node_34("📄 UpdateCategoryAction.php")
    node_30 --> node_35["📂 Product/"]
    node_35 --> node_36("📄 CreateProductAction.php")
    node_35 --> node_37("📄 DeleteProductAction.php")
    node_35 --> node_38("📄 ListProductsAction.php")
    node_35 --> node_39("📄 UpdateProductAction.php")
    node_24 --> node_40["📂 Dashboard/"]
    node_40 --> node_41("📄 ViewDashboardAction.php")
    node_24 --> node_42["📂 Sales/"]
    node_42 --> node_43["📂 Order/"]
    node_43 --> node_44("📄 ListOrdersAction.php")
    node_43 --> node_45("📄 UpdateOrderStatusAction.php")
    node_43 --> node_46("📄 ViewOrderDetailsAction.php")
    node_42 --> node_47["📂 Voucher/"]
    node_47 --> node_48("📄 CreateVoucherAction.php")
    node_47 --> node_49("📄 ListVouchersAction.php")
    node_22 --> node_50["📂 Repositories/"]
    node_21 --> node_51("📄 AlphaContainer.php")
    node_21 --> node_52["📂 Auth/"]
    node_52 --> node_53["📂 Middleware/"]
    node_53 --> node_54("📄 AdminSessionMiddleware.php")
    node_53 --> node_55("📄 LanguageMiddleware.php")
    node_53 --> node_56("📄 LegacyRouteRedirectMiddleware.php")
    node_53 --> node_57("📄 SessionMiddleware.php")
    node_53 --> node_58("📄 SignatureMiddleware.php")
    node_52 --> node_59["📂 Services/"]
    node_59 --> node_60("📄 AbstractAuthService.php")
    node_59 --> node_61("📄 AdminAuthService.php")
    node_59 --> node_62("📄 AuthServiceInterface.php")
    node_59 --> node_63("📄 CustomerAuthService.php")
    node_21 --> node_64["📂 Controller/"]
    node_64 --> node_65["📂 Actions/"]
    node_65 --> node_66("📄 ActionInterface.php")
    node_65 --> node_67["📂 Cart/"]
    node_67 --> node_68("📄 AddCartAction.php")
    node_67 --> node_69("📄 CalculateVisitorCartAction.php")
    node_67 --> node_70("📄 CartAction.php")
    node_67 --> node_71("📄 Checkout.php")
    node_67 --> node_72("📄 EditCartAction.php")
    node_67 --> node_73("📄 RemoveCartAction.php")
    node_67 --> node_74("📄 SaveShippingCepAction.php")
    node_67 --> node_75("📄 ShowCartAction.php")
    node_67 --> node_76("📄 ShowSuccessAction.php")
    node_67 --> node_77("📄 SubmitCheckoutAction.php")
    node_67 --> node_78("📄 SyncCartAction.php")
    node_65 --> node_79["📂 Category/"]
    node_79 --> node_80("📄 ShowCategoryAction.php")
    node_65 --> node_81["📂 Customer/"]
    node_81 --> node_82["📂 Account/"]
    node_82 --> node_83("📄 WishlistAction.php")
    node_81 --> node_84["📂 Addresses/"]
    node_84 --> node_85("📄 CreateAddressAction.php")
    node_84 --> node_86("📄 DeleteAddressAction.php")
    node_84 --> node_87("📄 EditAddressAction.php")
    node_84 --> node_88("📄 ShowAddressesAction.php")
    node_81 --> node_89["📂 Auth/"]
    node_89 --> node_90("📄 AccountAction.php")
    node_89 --> node_91("📄 LoginAction.php")
    node_89 --> node_92("📄 LogoutAction.php")
    node_89 --> node_93("📄 RegisterAction.php")
    node_89 --> node_94("📄 ShowLoginFormAction.php")
    node_89 --> node_95("📄 ShowRegistrationFormAction.php")
    node_81 --> node_96("📄 OrderHistoryAction.php")
    node_81 --> node_97("📄 OrdersAction.php")
    node_65 --> node_98["📂 Information/"]
    node_98 --> node_99("📄 ShowContactAction.php")
    node_98 --> node_100("📄 ShowInformationAction.php")
    node_98 --> node_101("📄 ShowSitemapAction.php")
    node_65 --> node_102["📂 Location/"]
    node_102 --> node_103("📄 GetZonesAction.php")
    node_65 --> node_104["📂 Main/"]
    node_104 --> node_105("📄 HomeAction.php")
    node_65 --> node_106["📂 Product/"]
    node_106 --> node_107("📄 ListProductsAction.php")
    node_106 --> node_108("📄 ProductReturnsAction.php")
    node_106 --> node_109("📄 SearchAction.php")
    node_106 --> node_110("📄 SearchProductsAction.php")
    node_106 --> node_111("📄 ShowProductAction.php")
    node_65 --> node_112("📄 RedirectToDefaultLanguageAction.php")
    node_64 --> node_113["📂 Api/"]
    node_113 --> node_114("📄 ApiProductController.php")
    node_64 --> node_115["📂 Auth/"]
    node_115 --> node_116("📄 LoginController.php")
    node_115 --> node_117("📄 LogoutController.php")
    node_64 --> node_118("📄 BaseController.php")
    node_64 --> node_119("📄 MainRouterController.php")
    node_64 --> node_120["📂 Web/"]
    node_120 --> node_121("📄 DashboardController.php")
    node_120 --> node_122("📄 ProductController.php")
    node_21 --> node_123["📂 Mappers/"]
    node_123 --> node_124("📄 AbstractMapper.php")
    node_123 --> node_125("📄 BaseMapper.php")
    node_123 --> node_126("📄 CollectionToArrayConverter.php")
    node_123 --> node_127["📂 EntityMappers/"]
    node_127 --> node_128("📄 AddressFormatMapper.php")
    node_127 --> node_129("📄 AddressMapper.php")
    node_127 --> node_130("📄 ApiHistoryMapper.php")
    node_127 --> node_131("📄 ApiIpMapper.php")
    node_127 --> node_132("📄 ArticleMapper.php")
    node_127 --> node_133("📄 AttributeGroupMapper.php")
    node_127 --> node_134("📄 AttributeMapper.php")
    node_127 --> node_135("📄 BannerMapper.php")
    node_127 --> node_136("📄 CartMapper.php")
    node_127 --> node_137("📄 CategoryMapper.php")
    node_127 --> node_138("📄 CountryMapper.php")
    node_127 --> node_139("📄 CouponMapper.php")
    node_127 --> node_140("📄 CronMapper.php")
    node_127 --> node_141("📄 CurrencyMapper.php")
    node_127 --> node_142("📄 CustomFieldMapper.php")
    node_127 --> node_143("📄 CustomerAffiliateMapper.php")
    node_127 --> node_144("📄 CustomerAuthorizeMapper.php")
    node_127 --> node_145("📄 CustomerGroupMapper.php")
    node_127 --> node_146("📄 CustomerMapper.php")
    node_127 --> node_147("📄 CustomerRewardMapper.php")
    node_127 --> node_148("📄 CustomerTokenMapper.php")
    node_127 --> node_149("📄 CustomerTransactionMapper.php")
    node_127 --> node_150("📄 EventMapper.php")
    node_127 --> node_151("📄 ExtensionMapper.php")
    node_127 --> node_152("📄 GdprMapper.php")
    node_127 --> node_153("📄 GeoZoneMapper.php")
    node_127 --> node_154("📄 HeaderMapper.php")
    node_127 --> node_155("📄 HomeMapper.php")
    node_127 --> node_156("📄 InformationMapper.php")
    node_127 --> node_157("📄 LanguageMapper.php")
    node_127 --> node_158("📄 LayoutMapper.php")
    node_127 --> node_159("📄 LayoutModuleMapper.php")
    node_127 --> node_160("📄 LengthClassMapper.php")
    node_127 --> node_161("📄 LocationMapper.php")
    node_127 --> node_162("📄 ManufacturerMapper.php")
    node_127 --> node_163("📄 ModuleMapper.php")
    node_127 --> node_164("📄 OrderMapper.php")
    node_127 --> node_165("📄 OrderReturnMapper.php")
    node_127 --> node_166("📄 PaymentMapper.php")
    node_127 --> node_167("📄 ProductDiscountMapper.php")
    node_127 --> node_168("📄 ProductImageMapper.php")
    node_127 --> node_169("📄 ProductMapper.php")
    node_127 --> node_170("📄 ProductOptionMapper.php")
    node_127 --> node_171("📄 ProductOptionValueMapper.php")
    node_127 --> node_172("📄 ReturnActionMapper.php")
    node_127 --> node_173("📄 ReturnHistoryMapper.php")
    node_127 --> node_174("📄 ReturnReasonMapper.php")
    node_127 --> node_175("📄 ReturnStatusMapper.php")
    node_127 --> node_176("📄 ReviewMapper.php")
    node_127 --> node_177("📄 SeoUrlMapper.php")
    node_127 --> node_178("📄 SessionMapper.php")
    node_127 --> node_179("📄 SettingMapper.php")
    node_127 --> node_180("📄 ShippingMapper.php")
    node_127 --> node_181("📄 StartupMapper.php")
    node_127 --> node_182("📄 StockStatusMapper.php")
    node_127 --> node_183("📄 StoreMapper.php")
    node_127 --> node_184("📄 SubscriptionMapper.php")
    node_127 --> node_185("📄 TaxClassMapper.php")
    node_127 --> node_186("📄 TaxRateMapper.php")
    node_127 --> node_187("📄 TaxRuleMapper.php")
    node_127 --> node_188("📄 ThemeMapper.php")
    node_127 --> node_189("📄 TopicMapper.php")
    node_127 --> node_190("📄 TotalMapper.php")
    node_127 --> node_191("📄 TranslationMapper.php")
    node_127 --> node_192("📄 UploadMapper.php")
    node_127 --> node_193("📄 UserAuthorizeMapper.php")
    node_127 --> node_194("📄 UserGroupMapper.php")
    node_127 --> node_195("📄 UserLoginMapper.php")
    node_127 --> node_196("📄 UserMapper.php")
    node_127 --> node_197("📄 UserTokenMapper.php")
    node_127 --> node_198("📄 WeightClassMapper.php")
    node_127 --> node_199("📄 WishlistMapper.php")
    node_127 --> node_200("📄 ZoneMapper.php")
    node_123 --> node_201("📄 MapperFactory.php")
    node_123 --> node_202("📄 MapperInterface.php")
    node_123 --> node_203["📂 Observers/"]
    node_203 --> node_204("📄 OrderEmailObserver.php")
    node_203 --> node_205("📄 OrderObserverInterface.php")
    node_21 --> node_206["📂 Model/"]
    node_206 --> node_207["📂 DataAccessObject/"]
    node_207 --> node_208("📄 ConnectionDB.php")
    node_207 --> node_209("📄 DataAccessObject.php")
    node_207 --> node_210("📄 ProxyFactory.php")
    node_207 --> node_211("📄 QueryBuilder.php")
    node_207 --> node_212("📄 UnitOfWork.php")
    node_206 --> node_213["📂 DataTransferObject/"]
    node_213 --> node_214["📂 Attributes/"]
    node_214 --> node_215("📄 AllowHtml.php")
    node_214 --> node_216("📄 Validation.php")
    node_213 --> node_217("📄 BaseDTO.php")
    node_213 --> node_218("📄 ContactFormDTO.php")
    node_213 --> node_219("📄 ProductShowcaseDTO.php")
    node_213 --> node_220("📄 SessionDTO.php")
    node_213 --> node_221("📄 ValidationContextFactory.php")
    node_213 --> node_222("📄 ViewResponse.php")
    node_206 --> node_223["📂 Domain/"]
    node_223 --> node_224["📂 Attributes/"]
    node_224 --> node_225("📄 HasOne.php")
    node_224 --> node_226("📄 ManyToMany.php")
    node_224 --> node_227("📄 ManyToOne.php")
    node_224 --> node_228("📄 OneToMany.php")
    node_223 --> node_229("📄 BaseEntity.php")
    node_223 --> node_230["📂 DTOs/"]
    node_230 --> node_231("📄 CookieDataDTO.php")
    node_230 --> node_232("📄 HeaderDataDTO.php")
    node_230 --> node_233("📄 HomeDataDTO.php")
    node_230 --> node_234("📄 MaintenanceDataDTO.php")
    node_230 --> node_235("📄 OrderDataDTO.php")
    node_230 --> node_236("📄 PaginationDataDTO.php")
    node_223 --> node_237["📂 Entities/"]
    node_237 --> node_238("📄 Address.php")
    node_237 --> node_239("📄 AddressFormat.php")
    node_237 --> node_240("📄 Antispam.php")
    node_237 --> node_241("📄 Api.php")
    node_237 --> node_242("📄 ApiHistory.php")
    node_237 --> node_243("📄 ApiIp.php")
    node_237 --> node_244("📄 Article.php")
    node_237 --> node_245("📄 ArticleComment.php")
    node_237 --> node_246("📄 ArticleDescription.php")
    node_237 --> node_247("📄 ArticleRating.php")
    node_237 --> node_248("📄 ArticleToLayout.php")
    node_237 --> node_249("📄 ArticleToStore.php")
    node_237 --> node_250("📄 Attribute.php")
    node_237 --> node_251("📄 AttributeDescription.php")
    node_237 --> node_252("📄 AttributeGroup.php")
    node_237 --> node_253("📄 AttributeGroupDescription.php")
    node_237 --> node_254("📄 Banner.php")
    node_237 --> node_255("📄 BannerImage.php")
    node_237 --> node_256("📄 BaseEntity.php")
    node_237 --> node_257("📄 Cart.php")
    node_237 --> node_258("📄 Category.php")
    node_237 --> node_259("📄 CategoryDescription.php")
    node_237 --> node_260("📄 CategoryFilter.php")
    node_237 --> node_261("📄 CategoryPath.php")
    node_237 --> node_262("📄 CategoryToLayout.php")
    node_237 --> node_263("📄 CategoryToStore.php")
    node_237 --> node_264("📄 Country.php")
    node_237 --> node_265("📄 CountryDescription.php")
    node_237 --> node_266("📄 Coupon.php")
    node_237 --> node_267("📄 CouponCategory.php")
    node_237 --> node_268("📄 CouponHistory.php")
    node_237 --> node_269("📄 CouponProduct.php")
    node_237 --> node_270("📄 Cron.php")
    node_237 --> node_271("📄 Currency.php")
    node_237 --> node_272("📄 CustomField.php")
    node_237 --> node_273("📄 CustomFieldCustomerGroup.php")
    node_237 --> node_274("📄 CustomFieldDescription.php")
    node_237 --> node_275("📄 CustomFieldValue.php")
    node_237 --> node_276("📄 CustomFieldValueDescription.php")
    node_237 --> node_277["📂 Customer/"]
    node_237 --> node_278("📄 Customer.php")
    node_237 --> node_279("📄 CustomerActivity.php")
    node_237 --> node_280("📄 CustomerAffiliate.php")
    node_237 --> node_281("📄 CustomerAffiliateReport.php")
    node_237 --> node_282("📄 CustomerApproval.php")
    node_237 --> node_283("📄 CustomerAuthorize.php")
    node_237 --> node_284("📄 CustomerGroup.php")
    node_237 --> node_285("📄 CustomerGroupDescription.php")
    node_237 --> node_286("📄 CustomerHistory.php")
    node_237 --> node_287("📄 CustomerIp.php")
    node_237 --> node_288("📄 CustomerLogin.php")
    node_237 --> node_289("📄 CustomerOnline.php")
    node_237 --> node_290("📄 CustomerReward.php")
    node_237 --> node_291("📄 CustomerSearch.php")
    node_237 --> node_292("📄 CustomerToken.php")
    node_237 --> node_293("📄 CustomerTransaction.php")
    node_237 --> node_294("📄 CustomerWishlist.php")
    node_237 --> node_295("📄 Download.php")
    node_237 --> node_296("📄 DownloadDescription.php")
    node_237 --> node_297("📄 DownloadReport.php")
    node_237 --> node_298("📄 Event.php")
    node_237 --> node_299("📄 Extension.php")
    node_237 --> node_300("📄 ExtensionInstall.php")
    node_237 --> node_301("📄 ExtensionPath.php")
    node_237 --> node_302("📄 Filter.php")
    node_237 --> node_303("📄 FilterDescription.php")
    node_237 --> node_304("📄 FilterGroup.php")
    node_237 --> node_305("📄 FilterGroupDescription.php")
    node_237 --> node_306("📄 Gdpr.php")
    node_237 --> node_307["📂 Geo/"]
    node_307 --> node_308("📄 City.php")
    node_307 --> node_309("📄 Country.php")
    node_307 --> node_310("📄 Zone.php")
    node_237 --> node_311("📄 GeoZone.php")
    node_237 --> node_312("📄 Identifier.php")
    node_237 --> node_313("📄 Information.php")
    node_237 --> node_314("📄 InformationDescription.php")
    node_237 --> node_315("📄 InformationToLayout.php")
    node_237 --> node_316("📄 InformationToStore.php")
    node_237 --> node_317("📄 InjetarInterface.php")
    node_237 --> node_318("📄 Language.php")
    node_237 --> node_319("📄 Layout.php")
    node_237 --> node_320("📄 LayoutModule.php")
    node_237 --> node_321("📄 LayoutRoute.php")
    node_237 --> node_322("📄 LengthClass.php")
    node_237 --> node_323("📄 LengthClassDescription.php")
    node_237 --> node_324("📄 Location.php")
    node_237 --> node_325("📄 Manufacturer.php")
    node_237 --> node_326("📄 ManufacturerToLayout.php")
    node_237 --> node_327("📄 ManufacturerToStore.php")
    node_237 --> node_328("📄 Marketing.php")
    node_237 --> node_329("📄 MarketingReport.php")
    node_237 --> node_330("📄 Module.php")
    node_237 --> node_331("📄 Notification.php")
    node_237 --> node_332("📄 Option.php")
    node_237 --> node_333("📄 OptionDescription.php")
    node_237 --> node_334("📄 OptionValue.php")
    node_237 --> node_335("📄 OptionValueDescription.php")
    node_237 --> node_336("📄 Order.php")
    node_237 --> node_337("📄 OrderHistory.php")
    node_237 --> node_338("📄 OrderOption.php")
    node_237 --> node_339("📄 OrderProduct.php")
    node_237 --> node_340("📄 OrderReturn.php")
    node_237 --> node_341("📄 OrderStatus.php")
    node_237 --> node_342("📄 OrderSubscription.php")
    node_237 --> node_343("📄 OrderTotal.php")
    node_237 --> node_344("📄 Product.php")
    node_237 --> node_345("📄 ProductAttribute.php")
    node_237 --> node_346("📄 ProductCode.php")
    node_237 --> node_347("📄 ProductDescription.php")
    node_237 --> node_348("📄 ProductDiscount.php")
    node_237 --> node_349("📄 ProductFilter.php")
    node_237 --> node_350("📄 ProductImage.php")
    node_237 --> node_351("📄 ProductOption.php")
    node_237 --> node_352("📄 ProductOptionValue.php")
    node_237 --> node_353("📄 ProductRelated.php")
    node_237 --> node_354("📄 ProductReport.php")
    node_237 --> node_355("📄 ProductReward.php")
    node_237 --> node_356("📄 ProductSubscription.php")
    node_237 --> node_357("📄 ProductToCategory.php")
    node_237 --> node_358("📄 ProductToDownload.php")
    node_237 --> node_359("📄 ProductToLayout.php")
    node_237 --> node_360("📄 ProductToStore.php")
    node_237 --> node_361("📄 ProductViewed.php")
    node_237 --> node_362("📄 ReturnAction.php")
    node_237 --> node_363("📄 ReturnHistory.php")
    node_237 --> node_364("📄 ReturnReason.php")
    node_237 --> node_365("📄 ReturnStatus.php")
    node_237 --> node_366("📄 Review.php")
    node_237 --> node_367("📄 SeoUrl.php")
    node_237 --> node_368("📄 Session.php")
    node_237 --> node_369("📄 Setting.php")
    node_237 --> node_370("📄 Startup.php")
    node_237 --> node_371("📄 Statistics.php")
    node_237 --> node_372("📄 StockStatus.php")
    node_237 --> node_373("📄 Store.php")
    node_237 --> node_374("📄 Subscription.php")
    node_237 --> node_375("📄 SubscriptionHistory.php")
    node_237 --> node_376("📄 SubscriptionLog.php")
    node_237 --> node_377("📄 SubscriptionOption.php")
    node_237 --> node_378("📄 SubscriptionPlan.php")
    node_237 --> node_379("📄 SubscriptionPlanDescription.php")
    node_237 --> node_380("📄 SubscriptionProduct.php")
    node_237 --> node_381("📄 SubscriptionStatus.php")
    node_237 --> node_382["📂 Supplier/"]
    node_382 --> node_383("📄 Addresses.php")
    node_382 --> node_384("📄 Supplier.php")
    node_237 --> node_385("📄 TaxClass.php")
    node_237 --> node_386("📄 TaxRate.php")
    node_237 --> node_387("📄 TaxRateToCustomerGroup.php")
    node_237 --> node_388("📄 TaxRule.php")
    node_237 --> node_389("📄 Theme.php")
    node_237 --> node_390("📄 Topic.php")
    node_237 --> node_391("📄 TopicDescription.php")
    node_237 --> node_392("📄 TopicToLayout.php")
    node_237 --> node_393("📄 TopicToStore.php")
    node_237 --> node_394("📄 Translation.php")
    node_237 --> node_395("📄 Upload.php")
    node_237 --> node_396("📄 User.php")
    node_237 --> node_397("📄 UserAuthorize.php")
    node_237 --> node_398("📄 UserGroup.php")
    node_237 --> node_399("📄 UserLogin.php")
    node_237 --> node_400("📄 UserToken.php")
    node_237 --> node_401("📄 WeightClass.php")
    node_237 --> node_402("📄 WeightClassDescription.php")
    node_237 --> node_403("📄 Zone.php")
    node_237 --> node_404("📄 ZoneDescription.php")
    node_237 --> node_405("📄 ZoneToGeoZone.php")
    node_237 --> node_406("📄 lista.txt")
    node_223 --> node_407["📂 Factory/"]
    node_407 --> node_408("📄 SimpleObjectFactory.php")
    node_223 --> node_409("📄 InterfaceEntity.php")
    node_223 --> node_410["📂 Observers/"]
    node_410 --> node_411("📄 OrderEmailObserver.php")
    node_410 --> node_412("📄 OrderObserverInterface.php")
    node_223 --> node_413["📂 Repositories/"]
    node_413 --> node_414("📄 AbstractRepository.php")
    node_413 --> node_415("📄 AddressFormatRepository.php")
    node_413 --> node_416("📄 AddressRepository.php")
    node_413 --> node_417("📄 ApiHistoryRepository.php")
    node_413 --> node_418("📄 ApiIpRepository.php")
    node_413 --> node_419("📄 ArticleRepository.php")
    node_413 --> node_420("📄 AttributeRepository.php")
    node_413 --> node_421("📄 BannerRepository.php")
    node_413 --> node_422("📄 BaseRepositoryInterface.php")
    node_413 --> node_423("📄 CartRepository.php")
    node_413 --> node_424("📄 CategoryRepository.php")
    node_413 --> node_425("📄 ConfigurationRepository.php")
    node_413 --> node_426("📄 CookieRepository.php")
    node_413 --> node_428("📄 CouponRepository.php")
    node_413 --> node_429("📄 CronRepository.php")
    node_413 --> node_430("📄 CurrencyRepository.php")
    node_413 --> node_431("📄 CustomFieldRepository.php")
    node_413 --> node_432("📄 CustomerAffiliateRepository.php")
    node_413 --> node_433("📄 CustomerAuthorizeRepository.php")
    node_413 --> node_434("📄 CustomerGroupRepository.php")
    node_413 --> node_435("📄 CustomerRepository.php")
    node_413 --> node_436("📄 CustomerRewardRepository.php")
    node_413 --> node_437("📄 CustomerTokenRepository.php")
    node_413 --> node_438("📄 CustomerTransactionRepository.php")
    node_413 --> node_439("📄 DownloadRepository.php")
    node_413 --> node_440("📄 EventRepository.php")
    node_413 --> node_441("📄 ExtensionRepository.php")
    node_413 --> node_442("📄 FooterRepository.php")
    node_413 --> node_443("📄 GeoZoneRepository.php")
    node_413 --> node_444("📄 HeaderRepository.php")
    node_413 --> node_445("📄 HomeRepository.php")
    node_413 --> node_446("📄 InformationRepository.php")
    node_413 --> node_447("📄 LanguageRepository.php")
    node_413 --> node_448("📄 LayoutRepository.php")
    node_413 --> node_449("📄 LengthClassRepository.php")
    node_413 --> node_450("📄 MaintenanceRepository.php")
    node_413 --> node_451("📄 ManufacturerRepository.php")
    node_413 --> node_452("📄 MenuRepository.php")
    node_413 --> node_453("📄 OrderRepository.php")
    node_413 --> node_454("📄 OrderReturnRepository.php")
    node_413 --> node_455("📄 OrderStatusRepository.php")
    node_413 --> node_456("📄 PaginationRepository.php")
    node_413 --> node_457("📄 PriceRepository.php")
    node_413 --> node_458("📄 ProductDiscountRepository.php")
    node_413 --> node_459("📄 ProductImageRepository.php")
    node_413 --> node_460("📄 ProductOptionRepository.php")
    node_413 --> node_461("📄 ProductOptionValueRepository.php")
    node_413 --> node_462("📄 ProductRepository.php")
    node_413 --> node_463("📄 RepositoryFactory.php")
    node_413 --> node_464("📄 ReturnDictionaryRepository.php")
    node_413 --> node_465("📄 ReturnHistoryRepository.php")
    node_413 --> node_466("📄 SearchRepository.php")
    node_413 --> node_467("📄 SeoUrlRepository.php")
    node_413 --> node_468("📄 SessionRepository.php")
    node_413 --> node_469("📄 SettingRepository.php")
    node_413 --> node_470("📄 SitemapRepository.php")
    node_413 --> node_471("📄 StartupRepository.php")
    node_413 --> node_472("📄 StoreRepository.php")
    node_413 --> node_473("📄 SubscriptionRepository.php")
    node_413 --> node_474("📄 SubscriptionStatusRepository.php")
    node_413 --> node_475("📄 TaxClassRepository.php")
    node_413 --> node_476("📄 TaxRateRepository.php")
    node_413 --> node_477("📄 TaxRuleRepository.php")
    node_413 --> node_478("📄 ThemeRepository.php")
    node_413 --> node_479("📄 TranslationRepository.php")
    node_413 --> node_480("📄 UploadRepository.php")
    node_413 --> node_481("📄 UserAuthorizeRepository.php")
    node_413 --> node_482("📄 UserGroupRepository.php")
    node_413 --> node_483("📄 UserLoginRepository.php")
    node_413 --> node_484("📄 UserRepository.php")
    node_413 --> node_485("📄 UserTokenRepository.php")
    node_413 --> node_486("📄 VoucherRepository.php")
    node_413 --> node_487("📄 WeightClassRepository.php")
    node_413 --> node_488("📄 WishlistRepository.php")
    node_413 --> node_489("📄 ZoneRepository.php")
    node_21 --> node_490["📂 Services/"]
    node_490 --> node_491["📂 Menu/"]
    node_491 --> node_492("📄 CategoryMenuService.php")
    node_490 --> node_493["📂 Shipping/"]
    node_493 --> node_494("📄 FlatRateShippingService.php")
    node_493 --> node_495("📄 FreeShippingService.php")
    node_493 --> node_496("📄 WeightBasedShippingService.php")
    node_21 --> node_497["📂 Session/"]
    node_497 --> node_498("📄 AlphaSessionHandler.php")
    node_21 --> node_499["📂 Support/"]
    node_499 --> node_500("📄 AlphaString.php")
    node_499 --> node_501["📂 Cache/"]
    node_501 --> node_502("📄 CacheStrategyInterface.php")
    node_501 --> node_503("📄 FilesystemCacheStrategy.php")
    node_499 --> node_504("📄 Collection.php")
    node_499 --> node_505("📄 Config.php")
    node_499 --> node_506("📄 Currency.php")
    node_499 --> node_507("📄 Customer.php")
    node_499 --> node_508("📄 Document.php")
    node_499 --> node_509("📄 EntityHydrator.php")
    node_499 --> node_510("📄 EvolutionGenerator.php")
    node_499 --> node_511("📄 Language.php")
    node_499 --> node_512("📄 LazyCollection.php")
    node_499 --> node_513["📂 Presenters/"]
    node_513 --> node_514("📄 ImagePresenter.php")
    node_499 --> node_515("📄 Registry.php")
    node_499 --> node_516("📄 RequestHelper.php")
    node_499 --> node_517("📄 Session.php")
    node_499 --> node_518("📄 Tax.php")
    node_499 --> node_519["📂 Twig/"]
    node_519 --> node_520("📄 UrlExtension.php")
    node_499 --> node_521("📄 Url.php")
    node_499 --> node_522("📄 ViewHelper.php")
    node_499 --> node_523("📄 Weight.php")
    node_499 --> node_524("📄 autoloader_legacy.php")
    node_21 --> node_525["📂 View/"]
    node_525 --> node_526["📂 Errors/"]
    node_526 --> node_527("📄 404.twig")
    node_525 --> node_528("📄 ViewRenderer.php")
    node_21 --> node_529["📂 language/"]
    node_529 --> node_530["📂 en-gb/"]
    node_530 --> node_531["📂 account/"]
    node_531 --> node_532("📄 account.php")
    node_531 --> node_533("📄 address.php")
    node_531 --> node_534("📄 affiliate.php")
    node_531 --> node_535("📄 authorize.php")
    node_531 --> node_536("📄 download.php")
    node_531 --> node_537("📄 edit.php")
    node_531 --> node_538("📄 forgotten.php")
    node_531 --> node_539("📄 login.php")
    node_531 --> node_540("📄 logout.php")
    node_531 --> node_541("📄 newsletter.php")
    node_531 --> node_542("📄 order.php")
    node_531 --> node_543("📄 password.php")
    node_531 --> node_544("📄 payment_method.php")
    node_531 --> node_545("📄 register.php")
    node_531 --> node_546("📄 returns.php")
    node_531 --> node_547("📄 reward.php")
    node_531 --> node_548("📄 subscription.php")
    node_531 --> node_549("📄 success.php")
    node_531 --> node_550("📄 tracking.php")
    node_531 --> node_551("📄 transaction.php")
    node_531 --> node_552("📄 wishlist.php")
    node_530 --> node_553["📂 api/"]
    node_553 --> node_554("📄 affiliate.php")
    node_553 --> node_555("📄 cart.php")
    node_553 --> node_556("📄 customer.php")
    node_553 --> node_557("📄 order.php")
    node_553 --> node_558("📄 payment_address.php")
    node_553 --> node_559("📄 payment_method.php")
    node_553 --> node_560("📄 shipping_address.php")
    node_553 --> node_561("📄 shipping_method.php")
    node_553 --> node_562("📄 subscription.php")
    node_530 --> node_563["📂 checkout/"]
    node_563 --> node_564("📄 cart.php")
    node_563 --> node_565("📄 checkout.php")
    node_563 --> node_566("📄 confirm.php")
    node_563 --> node_567("📄 failure.php")
    node_563 --> node_568("📄 payment_address.php")
    node_563 --> node_569("📄 payment_method.php")
    node_563 --> node_570("📄 register.php")
    node_563 --> node_571("📄 shipping_address.php")
    node_563 --> node_572("📄 shipping_method.php")
    node_563 --> node_573("📄 success.php")
    node_530 --> node_574["📂 cms/"]
    node_574 --> node_575("📄 blog.php")
    node_574 --> node_576("📄 comment.php")
    node_530 --> node_577["📂 common/"]
    node_577 --> node_578("📄 cart.php")
    node_577 --> node_579("📄 cookie.php")
    node_577 --> node_580("📄 currency.php")
    node_577 --> node_581("📄 footer.php")
    node_577 --> node_582("📄 header.php")
    node_577 --> node_583("📄 language.php")
    node_577 --> node_584("📄 maintenance.php")
    node_577 --> node_585("📄 menu.php")
    node_577 --> node_586("📄 search.php")
    node_530 --> node_587["📂 cron/"]
    node_587 --> node_588("📄 cron.php")
    node_587 --> node_589("📄 subscription.php")
    node_530 --> node_590("📄 default.php")
    node_530 --> node_591("📄 en-gb.png")
    node_530 --> node_592["📂 error/"]
    node_592 --> node_593("📄 not_found.php")
    node_592 --> node_594("📄 permission.php")
    node_530 --> node_595["📂 information/"]
    node_595 --> node_596("📄 contact.php")
    node_595 --> node_597("📄 gdpr.php")
    node_595 --> node_598("📄 gdpr_success.php")
    node_595 --> node_599("📄 information.php")
    node_595 --> node_600("📄 sitemap.php")
    node_530 --> node_601["📂 mail/"]
    node_601 --> node_602("📄 affiliate.php")
    node_601 --> node_603("📄 authorize.php")
    node_601 --> node_604("📄 authorize_reset.php")
    node_601 --> node_605("📄 forgotten.php")
    node_601 --> node_606("📄 gdpr.php")
    node_601 --> node_607("📄 gdpr_delete.php")
    node_601 --> node_608("📄 order_add.php")
    node_601 --> node_609("📄 order_alert.php")
    node_601 --> node_610("📄 order_edit.php")
    node_601 --> node_611("📄 register.php")
    node_601 --> node_612("📄 review.php")
    node_601 --> node_613("📄 subscription.php")
    node_601 --> node_614("📄 subscription_alert.php")
    node_601 --> node_615("📄 transaction.php")
    node_530 --> node_616["📂 product/"]
    node_616 --> node_617("📄 category.php")
    node_616 --> node_618("📄 compare.php")
    node_616 --> node_619("📄 manufacturer.php")
    node_616 --> node_620("📄 product.php")
    node_616 --> node_621("📄 related.php")
    node_616 --> node_622("📄 review.php")
    node_616 --> node_623("📄 search.php")
    node_616 --> node_624("📄 special.php")
    node_616 --> node_625("📄 thumb.php")
    node_530 --> node_626["📂 tool/"]
    node_626 --> node_627("📄 upload.php")
    node_529 --> node_628["📂 fr-fr/"]
    node_628 --> node_629["📂 account/"]
    node_629 --> node_630("📄 account.php")
    node_629 --> node_631("📄 address.php")
    node_629 --> node_632("📄 affiliate.php")
    node_629 --> node_633("📄 authorize.php")
    node_629 --> node_634("📄 download.php")
    node_629 --> node_635("📄 edit.php")
    node_629 --> node_636("📄 forgotten.php")
    node_629 --> node_637("📄 login.php")
    node_629 --> node_638("📄 logout.php")
    node_629 --> node_639("📄 newsletter.php")
    node_629 --> node_640("📄 order.php")
    node_629 --> node_641("📄 password.php")
    node_629 --> node_642("📄 payment_method.php")
    node_629 --> node_643("📄 register.php")
    node_629 --> node_644("📄 returns.php")
    node_629 --> node_645("📄 reward.php")
    node_629 --> node_646("📄 subscription.php")
    node_629 --> node_647("📄 success.php")
    node_629 --> node_648("📄 tracking.php")
    node_629 --> node_649("📄 transaction.php")
    node_629 --> node_650("📄 wishlist.php")
    node_628 --> node_651["📂 api/"]
    node_651 --> node_652("📄 affiliate.php")
    node_651 --> node_653("📄 cart.php")
    node_651 --> node_654("📄 customer.php")
    node_651 --> node_655("📄 order.php")
    node_651 --> node_656("📄 payment_address.php")
    node_651 --> node_657("📄 payment_method.php")
    node_651 --> node_658("📄 shipping_address.php")
    node_651 --> node_659("📄 shipping_method.php")
    node_651 --> node_660("📄 subscription.php")
    node_628 --> node_661["📂 checkout/"]
    node_661 --> node_662("📄 cart.php")
    node_661 --> node_663("📄 checkout.php")
    node_661 --> node_664("📄 confirm.php")
    node_661 --> node_665("📄 failure.php")
    node_661 --> node_666("📄 payment_address.php")
    node_661 --> node_667("📄 payment_method.php")
    node_661 --> node_668("📄 register.php")
    node_661 --> node_669("📄 shipping_address.php")
    node_661 --> node_670("📄 shipping_method.php")
    node_661 --> node_671("📄 success.php")
    node_628 --> node_672["📂 cms/"]
    node_672 --> node_673("📄 blog.php")
    node_672 --> node_674("📄 comment.php")
    node_628 --> node_675["📂 common/"]
    node_675 --> node_676("📄 cart.php")
    node_675 --> node_677("📄 cookie.php")
    node_675 --> node_678("📄 currency.php")
    node_675 --> node_679("📄 footer.php")
    node_675 --> node_680("📄 header.php")
    node_675 --> node_681("📄 language.php")
    node_675 --> node_682("📄 maintenance.php")
    node_675 --> node_683("📄 menu.php")
    node_675 --> node_684("📄 search.php")
    node_628 --> node_685["📂 cron/"]
    node_685 --> node_686("📄 cron.php")
    node_685 --> node_687("📄 subscription.php")
    node_628 --> node_688("📄 default.php")
    node_628 --> node_689["📂 error/"]
    node_689 --> node_690("📄 not_found.php")
    node_689 --> node_691("📄 permission.php")
    node_628 --> node_692("📄 fr-fr.png")
    node_628 --> node_693["📂 information/"]
    node_693 --> node_694("📄 contact.php")
    node_693 --> node_695("📄 gdpr.php")
    node_693 --> node_696("📄 gdpr_success.php")
    node_693 --> node_697("📄 information.php")
    node_693 --> node_698("📄 sitemap.php")
    node_628 --> node_699["📂 mail/"]
    node_699 --> node_700("📄 affiliate.php")
    node_699 --> node_701("📄 authorize.php")
    node_699 --> node_702("📄 authorize_reset.php")
    node_699 --> node_703("📄 forgotten.php")
    node_699 --> node_704("📄 gdpr.php")
    node_699 --> node_705("📄 gdpr_delete.php")
    node_699 --> node_706("📄 order_add.php")
    node_699 --> node_707("📄 order_alert.php")
    node_699 --> node_708("📄 order_edit.php")
    node_699 --> node_709("📄 register.php")
    node_699 --> node_710("📄 review.php")
    node_699 --> node_711("📄 subscription.php")
    node_699 --> node_712("📄 subscription_alert.php")
    node_699 --> node_713("📄 transaction.php")
    node_628 --> node_714["📂 product/"]
    node_714 --> node_715("📄 category.php")
    node_714 --> node_716("📄 compare.php")
    node_714 --> node_717("📄 manufacturer.php")
    node_714 --> node_718("📄 product.php")
    node_714 --> node_719("📄 related.php")
    node_714 --> node_720("📄 review.php")
    node_714 --> node_721("📄 search.php")
    node_714 --> node_722("📄 special.php")
    node_714 --> node_723("📄 thumb.php")
    node_628 --> node_724["📂 tool/"]
    node_724 --> node_725("📄 upload.php")
    node_529 --> node_726["📂 pt-br/"]
    node_726 --> node_727["📂 account/"]
    node_727 --> node_728("📄 account.php")
    node_727 --> node_729("📄 address.php")
    node_727 --> node_730("📄 affiliate.php")
    node_727 --> node_731("📄 download.php")
    node_727 --> node_732("📄 edit.php")
    node_727 --> node_733("📄 forgotten.php")
    node_727 --> node_734("📄 login.php")
    node_727 --> node_735("📄 logout.php")
    node_727 --> node_736("📄 newsletter.php")
    node_727 --> node_737("📄 order.php")
    node_727 --> node_738("📄 password.php")
    node_727 --> node_739("📄 payment_method.php")
    node_727 --> node_740("📄 recurring.php")
    node_727 --> node_741("📄 register.php")
    node_727 --> node_742("📄 reset.php")
    node_727 --> node_743("📄 returns.php")
    node_727 --> node_744("📄 reward.php")
    node_727 --> node_745("📄 success.php")
    node_727 --> node_746("📄 tracking.php")
    node_727 --> node_747("📄 transaction.php")
    node_727 --> node_748("📄 voucher.php")
    node_727 --> node_749("📄 wishlist.php")
    node_726 --> node_750["📂 affiliate/"]
    node_750 --> node_751("📄 login.php")
    node_750 --> node_752("📄 register.php")
    node_750 --> node_753("📄 success.php")
    node_726 --> node_754["📂 api/"]
    node_754 --> node_755("📄 cart.php")
    node_754 --> node_756("📄 coupon.php")
    node_754 --> node_757("📄 currency.php")
    node_754 --> node_758("📄 customer.php")
    node_754 --> node_759("📄 login.php")
    node_754 --> node_760("📄 order.php")
    node_754 --> node_761("📄 payment.php")
    node_754 --> node_762("📄 reward.php")
    node_754 --> node_763("📄 shipping.php")
    node_754 --> node_764("📄 voucher.php")
    node_726 --> node_765["📂 checkout/"]
    node_765 --> node_766("📄 cart.php")
    node_765 --> node_767("📄 checkout.php")
    node_765 --> node_768("📄 failure.php")
    node_765 --> node_769("📄 payment_address.php")
    node_765 --> node_770("📄 payment_method.php")
    node_765 --> node_771("📄 register.php")
    node_765 --> node_772("📄 shipping_address.php")
    node_765 --> node_773("📄 shipping_method.php")
    node_765 --> node_774("📄 success.php")
    node_726 --> node_775["📂 common/"]
    node_775 --> node_776("📄 cart.php")
    node_775 --> node_777("📄 cookie.php")
    node_775 --> node_778("📄 currency.php")
    node_775 --> node_779("📄 footer.php")
    node_775 --> node_780("📄 header.php")
    node_775 --> node_781("📄 home.php")
    node_775 --> node_782("📄 language.php")
    node_775 --> node_783("📄 maintenance.php")
    node_775 --> node_784("📄 menu.php")
    node_775 --> node_785("📄 search.php")
    node_726 --> node_786("📄 default.php")
    node_726 --> node_787["📂 error/"]
    node_787 --> node_788("📄 not_found.php")
    node_726 --> node_789["📂 extension/"]
    node_789 --> node_790["📂 captcha/"]
    node_790 --> node_791("📄 basic.php")
    node_790 --> node_792("📄 google.php")
    node_789 --> node_793["📂 credit_card/"]
    node_793 --> node_794("📄 sagepay_direct.php")
    node_793 --> node_795("📄 sagepay_server.php")
    node_793 --> node_796("📄 squareup.php")
    node_789 --> node_797["📂 module/"]
    node_797 --> node_798("📄 account.php")
    node_797 --> node_799("📄 amazon_login.php")
    node_797 --> node_800("📄 amazon_pay.php")
    node_797 --> node_801("📄 bestseller.php")
    node_797 --> node_802("📄 category.php")
    node_797 --> node_803("📄 divido_calculator.php")
    node_797 --> node_804("📄 ebay_listing.php")
    node_797 --> node_805("📄 featured.php")
    node_797 --> node_806("📄 filter.php")
    node_797 --> node_807("📄 google_hangouts.php")
    node_797 --> node_808("📄 information.php")
    node_797 --> node_809("📄 latest.php")
    node_797 --> node_810("📄 laybuy_layout.php")
    node_797 --> node_811("📄 special.php")
    node_797 --> node_812("📄 store.php")
    node_789 --> node_813["📂 openbay/"]
    node_813 --> node_814("📄 amazon_order.php")
    node_813 --> node_815("📄 amazonus_order.php")
    node_813 --> node_816("📄 ebay_order.php")
    node_813 --> node_817("📄 etsy_order.php")
    node_789 --> node_818["📂 payment/"]
    node_818 --> node_819("📄 alipay.php")
    node_818 --> node_820("📄 alipay_cross.php")
    node_818 --> node_821("📄 amazon_login_pay.php")
    node_818 --> node_822("📄 authorizenet_aim.php")
    node_818 --> node_823("📄 authorizenet_sim.php")
    node_818 --> node_824("📄 bank_transfer.php")
    node_818 --> node_825("📄 bluepay_hosted.php")
    node_818 --> node_826("📄 bluepay_redirect.php")
    node_818 --> node_827("📄 cardconnect.php")
    node_818 --> node_828("📄 cardinity.php")
    node_818 --> node_829("📄 cheque.php")
    node_818 --> node_830("📄 cod.php")
    node_818 --> node_831("📄 divido.php")
    node_818 --> node_832("📄 eway.php")
    node_818 --> node_833("📄 firstdata.php")
    node_818 --> node_834("📄 firstdata_remote.php")
    node_818 --> node_835("📄 free_checkout.php")
    node_818 --> node_836("📄 g2apay.php")
    node_818 --> node_837("📄 globalpay.php")
    node_818 --> node_838("📄 globalpay_remote.php")
    node_818 --> node_839("📄 klarna_account.php")
    node_818 --> node_840("📄 klarna_checkout.php")
    node_818 --> node_841("📄 klarna_invoice.php")
    node_818 --> node_842("📄 laybuy.php")
    node_818 --> node_843("📄 liqpay.php")
    node_818 --> node_844("📄 nochex.php")
    node_818 --> node_845("📄 paymate.php")
    node_818 --> node_846("📄 paypoint.php")
    node_818 --> node_847("📄 payza.php")
    node_818 --> node_848("📄 perpetual_payments.php")
    node_818 --> node_849("📄 pilibaba.php")
    node_818 --> node_850("📄 pp_braintree.php")
    node_818 --> node_851("📄 pp_express.php")
    node_818 --> node_852("📄 pp_payflow.php")
    node_818 --> node_853("📄 pp_payflow_iframe.php")
    node_818 --> node_854("📄 pp_pro.php")
    node_818 --> node_855("📄 pp_pro_iframe.php")
    node_818 --> node_856("📄 pp_standard.php")
    node_818 --> node_857("📄 realex.php")
    node_818 --> node_858("📄 realex_remote.php")
    node_818 --> node_859("📄 sagepay_direct.php")
    node_818 --> node_860("📄 sagepay_server.php")
    node_818 --> node_861("📄 sagepay_us.php")
    node_818 --> node_862("📄 securetrading_pp.php")
    node_818 --> node_863("📄 securetrading_ws.php")
    node_818 --> node_864("📄 skrill.php")
    node_818 --> node_865("📄 squareup.php")
    node_818 --> node_866("📄 twocheckout.php")
    node_818 --> node_867("📄 web_payment_software.php")
    node_818 --> node_868("📄 worldpay.php")
    node_789 --> node_869["📂 recurring/"]
    node_869 --> node_870("📄 pp_express.php")
    node_869 --> node_871("📄 squareup.php")
    node_789 --> node_872["📂 shipping/"]
    node_872 --> node_873("📄 auspost.php")
    node_872 --> node_874("📄 citylink.php")
    node_872 --> node_875("📄 ec_ship.php")
    node_872 --> node_876("📄 fedex.php")
    node_872 --> node_877("📄 flat.php")
    node_872 --> node_878("📄 free.php")
    node_872 --> node_879("📄 item.php")
    node_872 --> node_880("📄 parcelforce_48.php")
    node_872 --> node_881("📄 pickup.php")
    node_872 --> node_882("📄 pilibaba.php")
    node_872 --> node_883("📄 royal_mail.php")
    node_872 --> node_884("📄 ups.php")
    node_872 --> node_885("📄 usps.php")
    node_872 --> node_886("📄 weight.php")
    node_789 --> node_887["📂 total/"]
    node_887 --> node_888("📄 coupon.php")
    node_887 --> node_889("📄 credit.php")
    node_887 --> node_890("📄 handling.php")
    node_887 --> node_891("📄 klarna_fee.php")
    node_887 --> node_892("📄 low_order_fee.php")
    node_887 --> node_893("📄 reward.php")
    node_887 --> node_894("📄 shipping.php")
    node_887 --> node_895("📄 sub_total.php")
    node_887 --> node_896("📄 total.php")
    node_887 --> node_897("📄 voucher.php")
    node_726 --> node_898["📂 information/"]
    node_898 --> node_899("📄 contact.php")
    node_898 --> node_900("📄 information.php")
    node_898 --> node_901("📄 sitemap.php")
    node_898 --> node_902("📄 tracking.php")
    node_726 --> node_903["📂 mail/"]
    node_903 --> node_904("📄 affiliate.php")
    node_903 --> node_905("📄 forgotten.php")
    node_903 --> node_906("📄 order_add.php")
    node_903 --> node_907("📄 order_alert.php")
    node_903 --> node_908("📄 order_edit.php")
    node_903 --> node_909("📄 register.php")
    node_903 --> node_910("📄 review.php")
    node_903 --> node_911("📄 transaction.php")
    node_903 --> node_912("📄 voucher.php")
    node_726 --> node_913["📂 product/"]
    node_913 --> node_914("📄 category.php")
    node_913 --> node_915("📄 compare.php")
    node_913 --> node_916("📄 manufacturer.php")
    node_913 --> node_917("📄 product.php")
    node_913 --> node_918("📄 search.php")
    node_913 --> node_919("📄 special.php")
    node_726 --> node_920("📄 pt-br.php")
    node_726 --> node_921("📄 pt-br.png")
    node_726 --> node_922["📂 tool/"]
    node_922 --> node_923("📄 upload.php")
    root --> node_924["📂 data_base_new_schema/"]
    node_924 --> node_925("📄 db_schema.php")
    root --> node_926("📄 diagrama_de_arquitetura.mmd")
    root --> node_927["📂 diagrams/"]
    node_927 --> node_928("📄 diagrama-de-pastas.puml")
    node_927 --> node_929("📄 diagrama_de_arquitetura.mmd")
    node_927 --> node_930("📄 diagrama_de_pastas.mmd")
    root --> node_931["📂 docs/"]
    node_931 --> node_932("📄 ALPHA_ENGINE_ARCHITECTURE.md")
    node_931 --> node_933("📄 README1.md")
    node_931 --> node_934("📄 README4.md")
    node_931 --> node_935("📄 anti_patterns.md")
    node_931 --> node_936("📄 auth_progress.md")
    node_931 --> node_937("📄 cart_progress.md")
    node_931 --> node_938("📄 catalog_progress.md")
    node_931 --> node_939("📄 currency_progress.md")
    node_931 --> node_940("📄 page_structure.md")
    node_931 --> node_941("📄 pks_fks_bigint_feasibility.md")
    node_931 --> node_942("📄 session_decoupling_analysis.md")
    root --> node_943("📄 error.html")
    root --> node_944("📄 estrategia_a_serem_adotadas.md")
    root --> node_945("📄 index.old")
    root --> node_946["📂 lib/"]
    node_946 --> node_947("📄 libncurses.so.5")
    node_946 --> node_948("📄 libtinfo.so.5")
    root --> node_949("📄 nota_20260602_120000.md")
    root --> node_950("📄 nota_20260602_120530.md")
    root --> node_951("📄 nota_20260602_121500.md")
    root --> node_952("📄 nota_20260602_122500.md")
    root --> node_953("📄 nota_20260602_123500.md")
    root --> node_954("📄 nota_20260602_124500.md")
    root --> node_955("📄 nota_20260603_120000.md")
    root --> node_956("📄 nota_20260603_121000.md")
    root --> node_957("📄 nota_20260603_121500.md")
    root --> node_958("📄 nota_20260603_180000 Lembrete de Fim de Expediente: Status Atual da Migração Alpha Engine.md")
    root --> node_959("📄 php.ini")
    root --> node_960["📂 public_html/"]
    node_960 --> node_961("📄 .htaccess")
    node_960 --> node_962["📂 LPDHED2dC7Gjrg2b/"]
    node_962 --> node_963("📄 .htaccess")
    node_962 --> node_964("📄 index.php")
    node_960 --> node_965["📂 css/"]
    node_965 --> node_966["📂 admin/"]
    node_966 --> node_967("📄 admin.css")
    node_966 --> node_968("📄 components.css")
    node_966 --> node_969("📄 layout.css")
    node_966 --> node_970("📄 variables.css")
    node_965 --> node_971("📄 app.css")
    node_965 --> node_972["📂 assets/"]
    node_972 --> node_973["📂 css/"]
    node_965 --> node_974["📂 custom/"]
    node_974 --> node_975("📄 new-stylesheet.css")
    node_974 --> node_976("📄 personalizada.css")
    node_960 --> node_977("📄 favicon.ico")
    node_960 --> node_978["📂 fonts/"]
    node_978 --> node_979["📂 fontawesome/"]
    node_979 --> node_980("📄 LICENSE.txt")
    node_979 --> node_981["📂 css/"]
    node_981 --> node_982("📄 all.css")
    node_981 --> node_983("📄 all.min.css")
    node_981 --> node_984("📄 brands.css")
    node_981 --> node_985("📄 brands.min.css")
    node_981 --> node_986("📄 fontawesome.css")
    node_981 --> node_987("📄 fontawesome.min.css")
    node_981 --> node_988("📄 regular.css")
    node_981 --> node_989("📄 regular.min.css")
    node_981 --> node_990("📄 solid.css")
    node_981 --> node_991("📄 solid.min.css")
    node_981 --> node_992("📄 svg-with-js.css")
    node_981 --> node_993("📄 svg-with-js.min.css")
    node_981 --> node_994("📄 v4-font-face.css")
    node_981 --> node_995("📄 v4-font-face.min.css")
    node_981 --> node_996("📄 v4-shims.css")
    node_981 --> node_997("📄 v4-shims.min.css")
    node_981 --> node_998("📄 v5-font-face.css")
    node_981 --> node_999("📄 v5-font-face.min.css")
    node_979 --> node_1000["📂 webfonts/"]
    node_1000 --> node_1001("📄 fa-brands-400.ttf")
    node_1000 --> node_1002("📄 fa-brands-400.woff2")
    node_1000 --> node_1003("📄 fa-regular-400.ttf")
    node_1000 --> node_1004("📄 fa-regular-400.woff2")
    node_1000 --> node_1005("📄 fa-solid-900.ttf")
    node_1000 --> node_1006("📄 fa-solid-900.woff2")
    node_1000 --> node_1007("📄 fa-v4compatibility.ttf")
    node_1000 --> node_1008("📄 fa-v4compatibility.woff2")
    node_960 --> node_1009["📂 img/"]
    node_1009 --> node_1010["📂 banners/"]
    node_1010 --> node_1011("📄 banner_01_argamassa_e_rejuntes_quartzolit.png.webp")
    node_1010 --> node_1012("📄 banner_05_argamassa_e_rejuntes_quartzolit.png.webp")
    node_1010 --> node_1013("📄 banner_08_argamassa_e_rejuntes_quartzolit.png.webp")
    node_1010 --> node_1014("📄 cart.png")
    node_1010 --> node_1015("📄 logo.png")
    node_1010 --> node_1016("📄 logo2.png")
    node_1009 --> node_1017("📄 logo.png")
    node_1009 --> node_1018("📄 logo2.png")
    node_1009 --> node_1019["📂 manufacturer/"]
    node_1019 --> node_1020("📄 Companhia_Siderúrgica_Nacional.jpg")
    node_1019 --> node_1021("📄 Krona-logo-2.jpg")
    node_1019 --> node_1022("📄 Logo-Ceramica-LaranjaL.jpg")
    node_1019 --> node_1023("📄 Logo-MGM.jpg")
    node_1019 --> node_1024("📄 Logo-Mebuki.jpg")
    node_1019 --> node_1025("📄 alianca-logo.jpg")
    node_1019 --> node_1026("📄 alumstar.jpg")
    node_1019 --> node_1027("📄 arames-brasil.jpg")
    node_1019 --> node_1028("📄 astra-logo-1.jpg")
    node_1019 --> node_1029("📄 astra-logo-2.jpg")
    node_1019 --> node_1030("📄 blukit-logo.jpg")
    node_1019 --> node_1031("📄 botinas-guerreiro-2.jpg")
    node_1019 --> node_1032("📄 botinas-guerreiro-logo-2.jpg")
    node_1019 --> node_1033("📄 botinas-guerreiro-logo.jpg")
    node_1019 --> node_1034("📄 brasilit-logo.jpg")
    node_1019 --> node_1035("📄 carmelo-fior-logo.jpg")
    node_1019 --> node_1036("📄 ceramica-almeida-logo-2.jpg")
    node_1019 --> node_1037("📄 ceramica-almeida-logo.jpg")
    node_1019 --> node_1038("📄 ceramica-nova-firenze-logo.jpg")
    node_1019 --> node_1039("📄 condifios-logo.jpg")
    node_1019 --> node_1040("📄 d-aco.jpg")
    node_1019 --> node_1041("📄 empresa_de_cimentos_liz_sa_logo.jpeg")
    node_1019 --> node_1042("📄 fame-logo.jpg")
    node_1019 --> node_1043("📄 formigres-logo (2).jpg")
    node_1019 --> node_1044("📄 formigres-logo-2.jpg")
    node_1019 --> node_1045("📄 fortlev-logo.jpg")
    node_1019 --> node_1046("📄 gerdal-logo.jpg")
    node_1019 --> node_1047("📄 godmix-logo.jpg")
    node_1019 --> node_1048("📄 grupo-almeida-logo.jpg")
    node_1019 --> node_1049("📄 grupo-baumgart-logo.jpg")
    node_1019 --> node_1050("📄 grupo-rocha-logo.jpg")
    node_1019 --> node_1051("📄 hervy-logo.jpg")
    node_1019 --> node_1052("📄 incopisos-logo.jpg")
    node_1019 --> node_1053("📄 index.html")
    node_1019 --> node_1054("📄 infibra-logo-2.jpg")
    node_1019 --> node_1055("📄 infibra-logo.jpg")
    node_1019 --> node_1056("📄 inovax-logo.jpg")
    node_1019 --> node_1057("📄 iraja-logo.jpg")
    node_1019 --> node_1058("📄 jetmix-logo.jpg")
    node_1019 --> node_1059("📄 kadesh.jpg")
    node_1019 --> node_1060("📄 krona-logo.jpg")
    node_1019 --> node_1061("📄 logo-3f.jpg")
    node_1019 --> node_1062("📄 logo-Canal-260x65.jpg")
    node_1019 --> node_1063("📄 logo-Grupo-Ceral.jpg")
    node_1019 --> node_1064("📄 logo-ISOMARMORE.jpg")
    node_1019 --> node_1065("📄 logo-Indusfios.jpg")
    node_1019 --> node_1066("📄 logo-Lucheti.jpg")
    node_1019 --> node_1067("📄 logo-Lukscolor.jpg")
    node_1019 --> node_1068("📄 logo-Portas_Meu_Lar.jpg")
    node_1019 --> node_1069("📄 logo-RW-Pias.jpg")
    node_1019 --> node_1070("📄 logo-Rodan.jpg")
    node_1019 --> node_1071("📄 logo-acofer.jpg")
    node_1019 --> node_1072("📄 logo-i9.jpg")
    node_1019 --> node_1073("📄 logo-itapex.jpg")
    node_1019 --> node_1074("📄 logo-japi.jpg")
    node_1019 --> node_1075("📄 logo-king-fer.jpg")
    node_1019 --> node_1076("📄 logo-metalflex.jpg")
    node_1019 --> node_1077("📄 logo-metalurgia-rocha.jpg")
    node_1019 --> node_1078("📄 logo-ponteiras-brec.jpg")
    node_1019 --> node_1079("📄 logo-roloflex.jpg")
    node_1019 --> node_1080("📄 logo-rorato-1.jpg")
    node_1019 --> node_1081("📄 logo-sampaflex.jpg")
    node_1019 --> node_1082("📄 logo_AKATO.jpg")
    node_1019 --> node_1083("📄 logo_Lider.jpg")
    node_1019 --> node_1084("📄 logo_ceramica-martins.jpg")
    node_1019 --> node_1085("📄 logo_nova_santamarina.jpg")
    node_1019 --> node_1086("📄 lorenzetti-logo.jpg")
    node_1019 --> node_1087("📄 luksnova-logo.jpg")
    node_1019 --> node_1088("📄 megatron-logo.jpg")
    node_1019 --> node_1089("📄 multilit-logo.jpg")
    node_1019 --> node_1090("📄 paupedras-logo.jpg")
    node_1019 --> node_1091("📄 quartzolit-logo.jpg")
    node_1019 --> node_1092("📄 radial-2.jpg")
    node_1019 --> node_1093("📄 radial-logo.jpg")
    node_1019 --> node_1094("📄 saint-gobain-marcas-logo.jpg")
    node_1019 --> node_1095("📄 sherwin-williams-logo.jpg")
    node_1019 --> node_1096("📄 thermoplast-logo.jpg")
    node_1019 --> node_1097("📄 tigre-logo.jpg")
    node_1019 --> node_1098("📄 tintas-iraja-logo.jpg")
    node_1019 --> node_1099("📄 vedacit-logo.jpg")
    node_1019 --> node_1100("📄 viapol-logo.jpg")
    node_1019 --> node_1101("📄 wurth-logo.jpg")
    node_1009 --> node_1102("📄 no-image.png")
    node_1009 --> node_1103["📂 product/"]
    node_1103 --> node_1104("📄 0023-0024-0025-0026-0027-0028-0029-0030-0031-tubo de pvc soldável (3).png")
    node_1103 --> node_1105("📄 0330-0331-0332-0333-0336-0337-0338-0339-0340-adaptador curto soldável.png")
    node_1103 --> node_1106("📄 0341-0342-0343-0344-0345-0346-0347-0348-0349-adaptador para caixa d'água soldável.png")
    node_1103 --> node_1107("📄 0360-0361-0362-0363-0364-0365-0366-0359-bucha de redução curta soldável.png")
    node_1103 --> node_1108("📄 0367-0368-0369-0370-0371-0372-0373-0374-0375-0376-0377-0378-0379-0380-bucha de redução soldável.png")
    node_1103 --> node_1109("📄 0382_Cap-Soldável.png")
    node_1103 --> node_1110("📄 0393 Curva 45° Soldável.png")
    node_1103 --> node_1111("📄 0402_Curva-de-transposição-soldável copiar.png")
    node_1103 --> node_1112("📄 0406_Curva-90°-Soldável.png")
    node_1103 --> node_1113("📄 0415-0416-0417-0418-0419-0420-0421-0422-0423-joelho 45° soldável_Sem Sombra.png")
    node_1103 --> node_1114("📄 0424.Joelho 90° Soldável_Sem Sombra.png")
    node_1103 --> node_1115("📄 0433.Joelho-90°-de-Redução-Soldável.png")
    node_1103 --> node_1116("📄 0435.Luva Soldável.png")
    node_1103 --> node_1117("📄 0444.Luva de Correr Soldável.png")
    node_1103 --> node_1118("📄 0450_Luva-de-Redução-Soldável.png")
    node_1103 --> node_1119("📄 0454.Tê Soldável.png")
    node_1103 --> node_1120("📄 0463_Te-de-Redução-Soldável.png")
    node_1103 --> node_1121("📄 0474_União-Soldável.png")
    node_1103 --> node_1122("📄 0483_Joelho-90°-Soldável-e-com-Rosca-(LR).png")
    node_1103 --> node_1123("📄 0487_Luva-Soldável-e-com-Rosca-(LR).png")
    node_1103 --> node_1124("📄 0493_tê soldável com rosca LR.png")
    node_1103 --> node_1125("📄 0497_Joelo 90° soldável com bucha de latão_Sem Sombra.png")
    node_1103 --> node_1126("📄 0501.Luva Soldável com Bucha de Latão_Sem Sombra.png")
    node_1103 --> node_1127("📄 0504_Tê soldável com bucha de latão.png")
    node_1103 --> node_1128("📄 0516-Adesivo-plástico-bisnaga-2023.png")
    node_1103 --> node_1129("📄 0517-Adesivo-plástico-bisnaga-2023.png")
    node_1103 --> node_1130("📄 0518-Adesivo-plástico-com-pincel-aplicador-sem-sombra.png")
    node_1103 --> node_1131("📄 1324.Colar de Tomada.png")
    node_1103 --> node_1132("📄 1804_1805_7844c9ff97.jpg")
    node_1103 --> node_1133("📄 202408__Resistencias-e-Duchas_Site_FSD0152_RESISTENCIA.jpg")
    node_1103 --> node_1134("📄 2151_2152_4e65139e50.jpg")
    node_1103 --> node_1135("📄 3219_3220_f274286d24.jpg")
    node_1103 --> node_1136("📄 3359_3360_4299_kibanho_4t_3_9b2919e530.jpg")
    node_1103 --> node_1137("📄 3359_3360_a7509f7b84.jpg")
    node_1103 --> node_1138("📄 4346_4347_2_a039e31468.png")
    node_1103 --> node_1139("📄 470x470.jpg")
    node_1103 --> node_1140("📄 5663_66ae538665.png")
    node_1103 --> node_1141("📄 Adessivo-plástico-frasco-PVC.png")
    node_1103 --> node_1142("📄 Fita-Veda-rosca-pose-nova embalagem.png")
    node_1103 --> node_1143("📄 Fita-Veda-rosca-pose.png")
    node_1103 --> node_1144("📄 Krona_adaptador_sem_sombra.png")
    node_1103 --> node_1145("📄 TUBO-SOLDAVEL-6M-TIGRE.png")
    node_1103 --> node_1146["📂 cimento_liz/"]
    node_1146 --> node_1147("📄 cimento_liz_cp_II_E_32_rs.png")
    node_1146 --> node_1148("📄 cimento_liz_cp_IV_E_32_rs.png")
    node_1103 --> node_1149("📄 ducha_fame_super_ducha_4t_220v_6800w_c_cano_30cm_1567720477_baa6_1800x1800.jpg")
    node_1103 --> node_1150("📄 index.html")
    node_1103 --> node_1151["📂 votoran/"]
    node_1151 --> node_1152("📄 cimento_votoran_estruturais_50kg.png")
    node_1151 --> node_1153("📄 cimento_votoran_todas_as_obras.png")
    node_1009 --> node_1154["📂 seamless/"]
    node_1154 --> node_1155("📄 Roof01.jpg")
    node_1154 --> node_1156("📄 Roof02.jpg")
    node_1154 --> node_1157("📄 Stucco4.jpg")
    node_1154 --> node_1158("📄 index.html")
    node_1154 --> node_1159("📄 scandinavian-roof-tile-seamless.jpg")
    node_960 --> node_1160("📄 index.php")
    node_960 --> node_1161("📄 index_unit_test.php")
    node_960 --> node_1162["📂 js/"]
    node_1162 --> node_1163("📄 app.js")
    node_1162 --> node_1164["📂 cart/"]
    node_1164 --> node_1165("📄 cart.js")
    node_1164 --> node_1166("📄 checkout.js")
    node_1162 --> node_1167["📂 custom/"]
    node_1167 --> node_1168("📄 automatic-address.js")
    node_1167 --> node_1169("📄 form-validator.js")
    node_1167 --> node_1170("📄 shipping-simulator.js")
    node_960 --> node_1171["📂 mockup-navegavel/"]
    node_1171 --> node_1172["📂 mockup2/"]
    node_1172 --> node_1173("📄 carrinho.html")
    node_1172 --> node_1174["📂 carrinho_arquivos/"]
    node_1174 --> node_1175("📄 all.min.css")
    node_1174 --> node_1176("📄 app.css")
    node_1174 --> node_1177("📄 app.js")
    node_1174 --> node_1178("📄 cart.js")
    node_1174 --> node_1179("📄 checkout.js")
    node_1174 --> node_1180("📄 form-validator.js")
    node_1174 --> node_1181("📄 logo2.png")
    node_1174 --> node_1182("📄 new-stylesheet.css")
    node_1174 --> node_1183("📄 no-image.png")
    node_1174 --> node_1184("📄 personalizada.css")
    node_1174 --> node_1185("📄 shipping-simulator.js")
    node_1172 --> node_1186("📄 categoria.html")
    node_1172 --> node_1187["📂 categoria_arquivos/"]
    node_1187 --> node_1188("📄 all.min.css")
    node_1187 --> node_1189("📄 app.css")
    node_1187 --> node_1190("📄 app.js")
    node_1187 --> node_1191("📄 cart.js")
    node_1187 --> node_1192("📄 checkout.js")
    node_1187 --> node_1193("📄 form-validator.js")
    node_1187 --> node_1194("📄 logo2.png")
    node_1187 --> node_1195("📄 new-stylesheet.css")
    node_1187 --> node_1196("📄 no-image.png")
    node_1187 --> node_1197("📄 personalizada.css")
    node_1172 --> node_1198("📄 checkout.html")
    node_1172 --> node_1199("📄 checkout2.html")
    node_1172 --> node_1200["📂 checkout2_arquivos/"]
    node_1200 --> node_1201("📄 all.min.css")
    node_1200 --> node_1202("📄 app.css")
    node_1200 --> node_1203("📄 app.js")
    node_1200 --> node_1204("📄 cart.js")
    node_1200 --> node_1205("📄 checkout.js")
    node_1200 --> node_1206("📄 form-validator.js")
    node_1200 --> node_1207("📄 logo2.png")
    node_1200 --> node_1208("📄 new-stylesheet.css")
    node_1200 --> node_1209("📄 personalizada.css")
    node_1172 --> node_1210("📄 checkout3.html")
    node_1172 --> node_1211["📂 checkout3_arquivos/"]
    node_1211 --> node_1212("📄 all.min.css")
    node_1211 --> node_1213("📄 app.css")
    node_1211 --> node_1214("📄 app.js")
    node_1211 --> node_1215("📄 cart.js")
    node_1211 --> node_1216("📄 checkout.js")
    node_1211 --> node_1217("📄 form-validator.js")
    node_1211 --> node_1218("📄 logo2.png")
    node_1211 --> node_1219("📄 new-stylesheet.css")
    node_1211 --> node_1220("📄 personalizada.css")
    node_1172 --> node_1221["📂 checkout_arquivos/"]
    node_1221 --> node_1222("📄 all.min.css")
    node_1221 --> node_1223("📄 app.css")
    node_1221 --> node_1224("📄 app.js")
    node_1221 --> node_1225("📄 cart.js")
    node_1221 --> node_1226("📄 checkout.js")
    node_1221 --> node_1227("📄 form-validator.js")
    node_1221 --> node_1228("📄 logo2.png")
    node_1221 --> node_1229("📄 new-stylesheet.css")
    node_1221 --> node_1230("📄 personalizada.css")
    node_1172 --> node_1231("📄 editar-endereco.html")
    node_1172 --> node_1232["📂 editar-endereco_arquivos/"]
    node_1232 --> node_1233("📄 all.min.css")
    node_1232 --> node_1234("📄 app.css")
    node_1232 --> node_1235("📄 app.js")
    node_1232 --> node_1236("📄 cart.js")
    node_1232 --> node_1237("📄 checkout.js")
    node_1232 --> node_1238("📄 form-validator.js")
    node_1232 --> node_1239("📄 logo2.png")
    node_1232 --> node_1240("📄 new-stylesheet.css")
    node_1232 --> node_1241("📄 personalizada.css")
    node_1172 --> node_1242("📄 enderecos.html")
    node_1172 --> node_1243["📂 enderecos_arquivos/"]
    node_1243 --> node_1244("📄 all.min.css")
    node_1243 --> node_1245("📄 app.css")
    node_1243 --> node_1246("📄 app.js")
    node_1243 --> node_1247("📄 cart.js")
    node_1243 --> node_1248("📄 checkout.js")
    node_1243 --> node_1249("📄 form-validator.js")
    node_1243 --> node_1250("📄 logo2.png")
    node_1243 --> node_1251("📄 new-stylesheet.css")
    node_1243 --> node_1252("📄 personalizada.css")
    node_1172 --> node_1253("📄 index.html")
    node_1172 --> node_1254["📂 index_arquivos/"]
    node_1254 --> node_1255("📄 all.min.css")
    node_1254 --> node_1256("📄 app.css")
    node_1254 --> node_1257("📄 app.js")
    node_1254 --> node_1258("📄 cart.js")
    node_1254 --> node_1259("📄 checkout.js")
    node_1254 --> node_1260("📄 form-validator.js")
    node_1254 --> node_1261("📄 logo2.png")
    node_1254 --> node_1262("📄 new-stylesheet.css")
    node_1254 --> node_1263("📄 personalizada.css")
    node_1172 --> node_1264("📄 minha-conta.html")
    node_1172 --> node_1265["📂 minha-conta_arquivos/"]
    node_1265 --> node_1266("📄 all.min.css")
    node_1265 --> node_1267("📄 app.css")
    node_1265 --> node_1268("📄 app.js")
    node_1265 --> node_1269("📄 cart.js")
    node_1265 --> node_1270("📄 checkout.js")
    node_1265 --> node_1271("📄 form-validator.js")
    node_1265 --> node_1272("📄 logo2.png")
    node_1265 --> node_1273("📄 new-stylesheet.css")
    node_1265 --> node_1274("📄 personalizada.css")
    node_1172 --> node_1275("📄 novo-endereco.html")
    node_1172 --> node_1276["📂 novo-endereco_arquivos/"]
    node_1276 --> node_1277("📄 all.min.css")
    node_1276 --> node_1278("📄 app.css")
    node_1276 --> node_1279("📄 app.js")
    node_1276 --> node_1280("📄 cart.js")
    node_1276 --> node_1281("📄 checkout.js")
    node_1276 --> node_1282("📄 form-validator.js")
    node_1276 --> node_1283("📄 logo2.png")
    node_1276 --> node_1284("📄 new-stylesheet.css")
    node_1276 --> node_1285("📄 personalizada.css")
    node_1172 --> node_1286("📄 pedido-14.html")
    node_1172 --> node_1287["📂 pedido-14_arquivos/"]
    node_1287 --> node_1288("📄 all.min.css")
    node_1287 --> node_1289("📄 app.css")
    node_1287 --> node_1290("📄 app.js")
    node_1287 --> node_1291("📄 cart.js")
    node_1287 --> node_1292("📄 checkout.js")
    node_1287 --> node_1293("📄 form-validator.js")
    node_1287 --> node_1294("📄 logo2.png")
    node_1287 --> node_1295("📄 new-stylesheet.css")
    node_1287 --> node_1296("📄 personalizada.css")
    node_1172 --> node_1297("📄 pedidos.html")
    node_1172 --> node_1298["📂 pedidos_arquivos/"]
    node_1298 --> node_1299("📄 all.min.css")
    node_1298 --> node_1300("📄 app.css")
    node_1298 --> node_1301("📄 app.js")
    node_1298 --> node_1302("📄 cart.js")
    node_1298 --> node_1303("📄 checkout.js")
    node_1298 --> node_1304("📄 form-validator.js")
    node_1298 --> node_1305("📄 logo2.png")
    node_1298 --> node_1306("📄 new-stylesheet.css")
    node_1298 --> node_1307("📄 personalizada.css")
    node_1172 --> node_1308("📄 produto.html")
    node_1172 --> node_1309["📂 produto_arquivos/"]
    node_1309 --> node_1310("📄 all.min.css")
    node_1309 --> node_1311("📄 app.css")
    node_1309 --> node_1312("📄 app.js")
    node_1309 --> node_1313("📄 cart.js")
    node_1309 --> node_1314("📄 checkout.js")
    node_1309 --> node_1315("📄 form-validator.js")
    node_1309 --> node_1316("📄 logo2.png")
    node_1309 --> node_1317("📄 new-stylesheet.css")
    node_1309 --> node_1318("📄 no-image.png")
    node_1309 --> node_1319("📄 personalizada.css")
    node_1309 --> node_1320("📄 shipping-simulator.js")
    node_1172 --> node_1321("📄 sucesso.html")
    node_1172 --> node_1322["📂 sucesso_arquivos/"]
    node_1322 --> node_1323("📄 all.min.css")
    node_1322 --> node_1324("📄 app.css")
    node_1322 --> node_1325("📄 app.js")
    node_1322 --> node_1326("📄 cart.js")
    node_1322 --> node_1327("📄 checkout.js")
    node_1322 --> node_1328("📄 form-validator.js")
    node_1322 --> node_1329("📄 logo2.png")
    node_1322 --> node_1330("📄 new-stylesheet.css")
    node_1322 --> node_1331("📄 personalizada.css")
    root --> node_1332["📂 resources/"]
    node_1332 --> node_1333["📂 views/"]
    node_1333 --> node_1334["📂 admin/"]
    node_1334 --> node_1335["📂 auth/"]
    node_1335 --> node_1336("📄 error.html.twig")
    node_1335 --> node_1337("📄 forgot_password.html.twig")
    node_1335 --> node_1338("📄 login.html.twig")
    node_1335 --> node_1339("📄 reset_password.html.twig")
    node_1334 --> node_1340["📂 components/"]
    node_1340 --> node_1341["📂 organisms/"]
    node_1341 --> node_1342("📄 sidebar.html.twig")
    node_1341 --> node_1343("📄 topbar.html.twig")
    node_1334 --> node_1344["📂 layouts/"]
    node_1344 --> node_1345("📄 base_auth.html.twig")
    node_1334 --> node_1346["📂 pages/"]
    node_1346 --> node_1347["📂 dashboard/"]
    node_1347 --> node_1348("📄 index.html.twig")
    node_1333 --> node_1349("📄 base.html.twig")
    node_1333 --> node_1350["📂 components/"]
    node_1350 --> node_1351["📂 atoms/"]
    node_1351 --> node_1352("📄 button.twig")
    node_1351 --> node_1353("📄 link.twig")
    node_1351 --> node_1354("📄 logo.twig")
    node_1351 --> node_1355("📄 menu-button.twig")
    node_1351 --> node_1356("📄 nav-link.twig")
    node_1350 --> node_1357["📂 molecules/"]
    node_1357 --> node_1358("📄 alert.twig")
    node_1357 --> node_1359("📄 breadcrumbs.twig")
    node_1357 --> node_1360("📄 card-register.twig")
    node_1357 --> node_1361("📄 card-user.twig")
    node_1357 --> node_1362("📄 dropdown-recursive.twig")
    node_1357 --> node_1363("📄 footer-column.twig")
    node_1357 --> node_1364("📄 form-group-password.twig")
    node_1357 --> node_1365("📄 form-group.twig")
    node_1357 --> node_1366("📄 nav-menu.twig")
    node_1357 --> node_1367("📄 pagination.html.twig")
    node_1357 --> node_1368("📄 top-nav.twig")
    node_1357 --> node_1369("📄 utility-bar.twig")
    node_1350 --> node_1370["📂 organisms/"]
    node_1370 --> node_1371("📄 aside_filters.html.twig")
    node_1370 --> node_1372("📄 department-menu.twig")
    node_1370 --> node_1373("📄 footer.twig")
    node_1370 --> node_1374("📄 form-login.twig")
    node_1370 --> node_1375("📄 header.twig")
    node_1333 --> node_1376("📄 home.html.twig")
    node_1333 --> node_1377["📂 layouts/"]
    node_1377 --> node_1378("📄 base.html.twig")
    node_1333 --> node_1379["📂 pages/"]
    node_1379 --> node_1380["📂 cart/"]
    node_1380 --> node_1381("📄 cart.twig")
    node_1380 --> node_1382("📄 checkout.twig")
    node_1380 --> node_1383("📄 payment_method.twig")
    node_1380 --> node_1384("📄 shipping-address.twig")
    node_1380 --> node_1385("📄 success.twig")
    node_1379 --> node_1386["📂 category/"]
    node_1386 --> node_1387("📄 show.html.twig")
    node_1379 --> node_1388["📂 errors/"]
    node_1388 --> node_1389("📄 404.html.twig")
    node_1379 --> node_1390["📂 information/"]
    node_1390 --> node_1391("📄 contact.twig")
    node_1390 --> node_1392("📄 show.html.twig")
    node_1390 --> node_1393("📄 sitemap.twig")
    node_1379 --> node_1394["📂 product/"]
    node_1394 --> node_1395("📄 product-card.html.twig")
    node_1394 --> node_1396("📄 product-returns.html.twig")
    node_1394 --> node_1397("📄 search-product.html.twig")
    node_1394 --> node_1398("📄 search.html.twig")
    node_1394 --> node_1399("📄 show.html.twig")
    node_1379 --> node_1400["📂 users/"]
    node_1400 --> node_1401["📂 accounts/"]
    node_1401 --> node_1402("📄 account.twig")
    node_1401 --> node_1403("📄 newsletter.twig")
    node_1401 --> node_1404("📄 order-history.twig")
    node_1401 --> node_1405("📄 orders.twig")
    node_1401 --> node_1406("📄 wishlist.twig")
    node_1400 --> node_1407["📂 addresses/"]
    node_1407 --> node_1408("📄 create.twig")
    node_1407 --> node_1409("📄 edit.twig")
    node_1407 --> node_1410("📄 index.twig")
    node_1400 --> node_1411("📄 edit.html.twig")
    node_1400 --> node_1412("📄 index.html.twig")
    node_1400 --> node_1413("📄 login.twig")
    node_1400 --> node_1414("📄 register.twig")
    node_1400 --> node_1415("📄 return.twig")
    root --> node_1416("📄 robots.txt")
    root --> node_1417["📂 tests/"]
    node_1417 --> node_1418["📂 scripts_uteis/"]
    node_1418 --> node_1419("📄 Gerador-automático-de-documentação-de-pastas.php")
    node_1418 --> node_1420["📂 NovoEnderecamento/"]
    node_1420 --> node_1421("📄 Como_ler_e_validar_esses_dados_no_seu_código.php")
    node_1420 --> node_1422("📄 CondadosSuecia.sql")
    node_1420 --> node_1423("📄 TodosEstadosBrasileiros.sql")
    node_1420 --> node_1424("📄 ValidaBloqueioNoCheckout.php")
    node_1420 --> node_1425("📄 consulta_cidade_pais_code.sql")
    node_1420 --> node_1426("📄 create-tables.sql")
    node_1420 --> node_1427("📄 create_address_supplies.sql")
    node_1420 --> node_1428("📄 insert_city")
    node_1420 --> node_1429("📄 insert_country.sql")
    node_1420 --> node_1430("📄 query_de_consulta_supplier.sql")
    node_1418 --> node_1431("📄 converter_tipos_das_PKs_e_FKs.sql")
    node_1418 --> node_1432("📄 estrutura.mmd")
    node_1418 --> node_1433("📄 estrutura.puml")
    node_1418 --> node_1434("📄 verifica-se-o-namespace-coincidem-com-a-classe.php")
    root --> node_1435("📄 wishlist.twig")
```
