@startfiles
.
├── .antigravityrc
├── .gitignore
├── 20240528_105000.md
├── Config/
│   └── Routes.php
├── Containers/
│   ├── AppBootstrap.php
│   └── AppContainer.php
├── Locales/
│   ├── en-gb/
│   │   ├── en-gb.account.account.json
│   │   ├── en-gb.account.returns.json
│   │   ├── en-gb.cart.json
│   │   ├── en-gb.checkout.json
│   │   ├── en-gb.common.json
│   │   ├── en-gb.home.json
│   │   ├── en-gb.information.sitemap.json
│   │   ├── en-gb.order.success.json
│   │   ├── en-gb.product.json
│   │   └── en-gb.product.search.json
│   └── pt-br/
│       ├── pt-br.account.account.json
│       ├── pt-br.account.returns.json
│       ├── pt-br.cart.json
│       ├── pt-br.checkout.json
│       ├── pt-br.common.json
│       ├── pt-br.home.json
│       ├── pt-br.information.sitemap.json
│       ├── pt-br.order.success.json
│       ├── pt-br.product.json
│       └── pt-br.product.search.json
├── LogsPersonalizados/
│   └── Log.php
├── README.md
├── composer.json
├── config.php
├── core/
│   ├── Admin/
│   │   ├── Controllers/
│   │   │   └── Actions/
│   │   │       ├── Auth/
│   │   │       │   ├── LoginAction.php
│   │   │       │   ├── LogoutAction.php
│   │   │       │   ├── ResetPasswordAction.php
│   │   │       │   ├── SetupAction.php
│   │   │       │   ├── ShowLoginAction.php
│   │   │       │   └── ShowSetupAction.php
│   │   │       ├── CRM/
│   │   │       │   └── Customer/
│   │   │       │       └── ListCustomersAction.php
│   │   │       ├── Catalog/
│   │   │       │   ├── Category/
│   │   │       │   │   ├── CreateCategoryAction.php
│   │   │       │   │   ├── DeleteCategoryAction.php
│   │   │       │   │   ├── EditCategoryAction.php
│   │   │       │   │   ├── ListCategoriesAction.php
│   │   │       │   │   └── UpdateCategoryAction.php
│   │   │       │   ├── Manufacturer/
│   │   │       │   │   ├── CreateManufacturerAction.php
│   │   │       │   │   ├── DeleteManufacturerAction.php
│   │   │       │   │   ├── EditManufacturerAction.php
│   │   │       │   │   ├── ListManufacturersAction.php
│   │   │       │   │   ├── StoreManufacturerAction.php
│   │   │       │   │   └── UpdateManufacturerAction.php
│   │   │       │   └── Product/
│   │   │       │       ├── CreateProductAction.php
│   │   │       │       ├── DeleteProductAction.php
│   │   │       │       ├── EditProductAction.php
│   │   │       │       ├── ListProductsAction.php
│   │   │       │       └── UpdateProductAction.php
│   │   │       ├── Customer/
│   │   │       │   ├── Address/
│   │   │       │   │   ├── CreateAddressAction.php
│   │   │       │   │   ├── DeleteAddressAction.php
│   │   │       │   │   └── EditAddressAction.php
│   │   │       │   └── Customer/
│   │   │       │       ├── CreateCustomerAction.php
│   │   │       │       ├── EditCustomerAction.php
│   │   │       │       ├── ListCustomersAction.php
│   │   │       │       └── ShowCustomerAction.php
│   │   │       ├── Dashboard/
│   │   │       │   └── ViewDashboardAction.php
│   │   │       ├── Procurement/
│   │   │       │   └── Supplier/
│   │   │       │       ├── CreateSupplierAction.php
│   │   │       │       ├── DeleteSupplierAction.php
│   │   │       │       ├── EditSupplierAction.php
│   │   │       │       ├── ListSuppliersAction.php
│   │   │       │       ├── StoreSupplierAction.php
│   │   │       │       └── UpdateSupplierAction.php
│   │   │       ├── Sales/
│   │   │       │   ├── Order/
│   │   │       │   │   ├── ListOrdersAction.php
│   │   │       │   │   ├── ShowOrderAction.php
│   │   │       │   │   ├── UpdateOrderStatusAction.php
│   │   │       │   │   └── ViewOrderDetailsAction.php
│   │   │       │   └── Voucher/
│   │   │       │       ├── CreateVoucherAction.php
│   │   │       │       └── ListVouchersAction.php
│   │   │       └── Setting/
│   │   │           └── StoreSetting/
│   │   │               ├── EditStoreSettingAction.php
│   │   │               └── UpdateStoreSettingAction.php
│   │   └── Repositories/
│   ├── AlphaContainer.php
│   ├── Auth/
│   │   ├── Middleware/
│   │   │   ├── AdminSessionMiddleware.php
│   │   │   ├── LanguageMiddleware.php
│   │   │   ├── LegacyRouteRedirectMiddleware.php
│   │   │   ├── SessionMiddleware.php
│   │   │   └── SignatureMiddleware.php
│   │   └── Services/
│   │       ├── AbstractAuthService.php
│   │       ├── AdminAuthService.php
│   │       ├── AuthServiceInterface.php
│   │       └── CustomerAuthService.php
│   ├── Controller/
│   │   ├── Actions/
│   │   │   ├── ActionInterface.php
│   │   │   ├── Cart/
│   │   │   │   ├── AddCartAction.php
│   │   │   │   ├── CalculateVisitorCartAction.php
│   │   │   │   ├── CartAction.php
│   │   │   │   ├── Checkout.php
│   │   │   │   ├── EditCartAction.php
│   │   │   │   ├── RemoveCartAction.php
│   │   │   │   ├── SaveShippingCepAction.php
│   │   │   │   ├── ShowCartAction.php
│   │   │   │   ├── ShowSuccessAction.php
│   │   │   │   ├── SubmitCheckoutAction.php
│   │   │   │   └── SyncCartAction.php
│   │   │   ├── Category/
│   │   │   │   └── ShowCategoryAction.php
│   │   │   ├── Checkout/
│   │   │   │   └── ProcessPaymentAction.php
│   │   │   ├── Customer/
│   │   │   │   ├── Account/
│   │   │   │   │   ├── NewsletterAction.php
│   │   │   │   │   ├── ShowTransactionAction
│   │   │   │   │   ├── TransactionAction.php
│   │   │   │   │   ├── UpdateAction.php
│   │   │   │   │   ├── WishlistAction.php
│   │   │   │   │   ├── WishlistAddAction.php
│   │   │   │   │   └── WishlistRemoveAction.php
│   │   │   │   ├── Addresses/
│   │   │   │   │   ├── CreateAddressAction.php
│   │   │   │   │   ├── DeleteAddressAction.php
│   │   │   │   │   ├── EditAddressAction.php
│   │   │   │   │   └── ShowAddressesAction.php
│   │   │   │   ├── Auth/
│   │   │   │   │   ├── AccountAction.php
│   │   │   │   │   ├── LoginAction.php
│   │   │   │   │   ├── LogoutAction.php
│   │   │   │   │   ├── RegisterAction.php
│   │   │   │   │   ├── RequestPasswordResetAction.php
│   │   │   │   │   ├── ResetPasswordAction.php
│   │   │   │   │   ├── ShowLoginFormAction.php
│   │   │   │   │   └── ShowRegistrationFormAction.php
│   │   │   │   ├── OrderHistoryAction.php
│   │   │   │   └── OrdersAction.php
│   │   │   ├── Information/
│   │   │   │   ├── ShowContactAction.php
│   │   │   │   ├── ShowInformationAction.php
│   │   │   │   └── ShowSitemapAction.php
│   │   │   ├── Location/
│   │   │   │   ├── GetGeoCitiesAction.php
│   │   │   │   ├── GetGeoZonesAction.php
│   │   │   │   └── GetZonesAction.php
│   │   │   ├── Main/
│   │   │   │   └── HomeAction.php
│   │   │   ├── Product/
│   │   │   │   ├── ListProductsAction.php
│   │   │   │   ├── ProductReturnsAction.php
│   │   │   │   ├── SearchAction.php
│   │   │   │   ├── SearchProductsAction.php
│   │   │   │   └── ShowProductAction.php
│   │   │   └── RedirectToDefaultLanguageAction.php
│   │   ├── Api/
│   │   │   └── ApiProductController.php
│   │   ├── Auth/
│   │   │   ├── LoginController.php
│   │   │   └── LogoutController.php
│   │   ├── BaseController.php
│   │   ├── MainRouterController.php
│   │   └── Web/
│   │       ├── DashboardController.php
│   │       └── ProductController.php
│   ├── Mappers/
│   │   ├── AbstractMapper.php
│   │   ├── BaseMapper.php
│   │   ├── CollectionToArrayConverter.php
│   │   ├── EntityMappers/
│   │   │   ├── AddressFormatMapper.php
│   │   │   ├── AddressMapper.php
│   │   │   ├── AddressesMapper.php
│   │   │   ├── ApiHistoryMapper.php
│   │   │   ├── ApiIpMapper.php
│   │   │   ├── ArticleMapper.php
│   │   │   ├── AttributeGroupMapper.php
│   │   │   ├── AttributeMapper.php
│   │   │   ├── BannerMapper.php
│   │   │   ├── CartMapper.php
│   │   │   ├── CategoryMapper.php
│   │   │   ├── CouponMapper.php
│   │   │   ├── CronMapper.php
│   │   │   ├── CurrencyMapper.php
│   │   │   ├── CustomerAddressesMapper.php
│   │   │   ├── CustomerAffiliateMapper.php
│   │   │   ├── CustomerAuthorizeMapper.php
│   │   │   ├── CustomerGroupMapper.php
│   │   │   ├── CustomerMapper.php
│   │   │   ├── CustomerRewardMapper.php
│   │   │   ├── CustomerTokenMapper.php
│   │   │   ├── CustomerTransactionMapper.php
│   │   │   ├── EventMapper.php
│   │   │   ├── ExtensionMapper.php
│   │   │   ├── GdprMapper.php
│   │   │   ├── GeoCityMapper.php
│   │   │   ├── GeoCountryMapper.php
│   │   │   ├── GeoZoneMapper.php
│   │   │   ├── HeaderMapper.php
│   │   │   ├── HomeMapper.php
│   │   │   ├── InformationMapper.php
│   │   │   ├── LanguageMapper.php
│   │   │   ├── LayoutMapper.php
│   │   │   ├── LayoutModuleMapper.php
│   │   │   ├── LengthClassMapper.php
│   │   │   ├── LocationMapper.php
│   │   │   ├── ManufacturerMapper.php
│   │   │   ├── ModuleMapper.php
│   │   │   ├── OrderMapper.php
│   │   │   ├── OrderReturnMapper.php
│   │   │   ├── OrderStatusMapper.php
│   │   │   ├── PaymentMapper.php
│   │   │   ├── ProductDiscountMapper.php
│   │   │   ├── ProductImageMapper.php
│   │   │   ├── ProductMapper.php
│   │   │   ├── ProductOptionMapper.php
│   │   │   ├── ProductOptionValueMapper.php
│   │   │   ├── ReturnActionMapper.php
│   │   │   ├── ReturnHistoryMapper.php
│   │   │   ├── ReturnReasonMapper.php
│   │   │   ├── ReturnStatusMapper.php
│   │   │   ├── ReviewMapper.php
│   │   │   ├── SeoUrlMapper.php
│   │   │   ├── SessionMapper.php
│   │   │   ├── SettingMapper.php
│   │   │   ├── ShippingMapper.php
│   │   │   ├── StartupMapper.php
│   │   │   ├── StockStatusMapper.php
│   │   │   ├── StoreMapper.php
│   │   │   ├── SubscriptionMapper.php
│   │   │   ├── SupplierMapper.php
│   │   │   ├── TaxClassMapper.php
│   │   │   ├── TaxRateMapper.php
│   │   │   ├── TaxRuleMapper.php
│   │   │   ├── ThemeMapper.php
│   │   │   ├── TopicMapper.php
│   │   │   ├── TotalMapper.php
│   │   │   ├── TranslationMapper.php
│   │   │   ├── UserAuthorizeMapper.php
│   │   │   ├── UserGroupMapper.php
│   │   │   ├── UserLoginMapper.php
│   │   │   ├── UserMapper.php
│   │   │   ├── UserTokenMapper.php
│   │   │   ├── WeightClassMapper.php
│   │   │   ├── WishlistMapper.php
│   │   │   └── ZoneMapper.php
│   │   ├── MapperFactory.php
│   │   ├── MapperInterface.php
│   │   └── Observers/
│   │       ├── OrderEmailObserver.php
│   │       └── OrderObserverInterface.php
│   ├── Model/
│   │   ├── DataAccessObject/
│   │   │   ├── ConnectionDB.php
│   │   │   ├── DataAccessObject.php
│   │   │   ├── ProxyFactory.php
│   │   │   ├── QueryBuilder.php
│   │   │   └── UnitOfWork.php
│   │   ├── DataTransferObject/
│   │   │   ├── Attributes/
│   │   │   │   ├── AllowHtml.php
│   │   │   │   └── Validation.php
│   │   │   ├── BaseDTO.php
│   │   │   ├── ContactFormDTO.php
│   │   │   ├── ProductShowcaseDTO.php
│   │   │   ├── SessionDTO.php
│   │   │   ├── ValidationContextFactory.php
│   │   │   └── ViewResponse.php
│   │   └── Domain/
│   │       ├── Attributes/
│   │       │   ├── HasOne.php
│   │       │   ├── ManyToMany.php
│   │       │   ├── ManyToOne.php
│   │       │   └── OneToMany.php
│   │       ├── BaseEntity.php
│   │       ├── DTOs/
│   │       │   ├── CookieDataDTO.php
│   │       │   ├── HeaderDataDTO.php
│   │       │   ├── HomeDataDTO.php
│   │       │   ├── MaintenanceDataDTO.php
│   │       │   ├── OrderDataDTO.php
│   │       │   └── PaginationDataDTO.php
│   │       ├── Entities/
│   │       │   ├── AddressFormat.php
│   │       │   ├── Antispam.php
│   │       │   ├── Api.php
│   │       │   ├── ApiHistory.php
│   │       │   ├── ApiIp.php
│   │       │   ├── Article.php
│   │       │   ├── ArticleComment.php
│   │       │   ├── ArticleDescription.php
│   │       │   ├── ArticleRating.php
│   │       │   ├── ArticleToLayout.php
│   │       │   ├── ArticleToStore.php
│   │       │   ├── Attribute.php
│   │       │   ├── AttributeDescription.php
│   │       │   ├── AttributeGroup.php
│   │       │   ├── AttributeGroupDescription.php
│   │       │   ├── Banner.php
│   │       │   ├── BannerImage.php
│   │       │   ├── BaseEntity.php
│   │       │   ├── Cart.php
│   │       │   ├── Category.php
│   │       │   ├── CategoryDescription.php
│   │       │   ├── CategoryFilter.php
│   │       │   ├── CategoryPath.php
│   │       │   ├── CategoryToLayout.php
│   │       │   ├── CategoryToStore.php
│   │       │   ├── CountryDeprecated.txt
│   │       │   ├── CountryDescriptionDeprecated.txt
│   │       │   ├── Coupon.php
│   │       │   ├── CouponCategory.php
│   │       │   ├── CouponHistory.php
│   │       │   ├── CouponProduct.php
│   │       │   ├── Cron.php
│   │       │   ├── Currency.php
│   │       │   ├── Customer/
│   │       │   │   ├── Customer.php
│   │       │   │   ├── CustomerActivity.php
│   │       │   │   ├── CustomerAddresses.php
│   │       │   │   ├── CustomerAffiliate.php
│   │       │   │   ├── CustomerAffiliateReport.php
│   │       │   │   ├── CustomerApproval.php
│   │       │   │   ├── CustomerAuthorize.php
│   │       │   │   ├── CustomerGroup.php
│   │       │   │   ├── CustomerGroupDescription.php
│   │       │   │   ├── CustomerHistory.php
│   │       │   │   ├── CustomerIp.php
│   │       │   │   ├── CustomerLogin.php
│   │       │   │   ├── CustomerOnline.php
│   │       │   │   ├── CustomerReward.php
│   │       │   │   ├── CustomerSearch.php
│   │       │   │   ├── CustomerToken.php
│   │       │   │   ├── CustomerTransaction.php
│   │       │   │   └── CustomerWishlist.php
│   │       │   ├── Event.php
│   │       │   ├── Extension.php
│   │       │   ├── ExtensionInstall.php
│   │       │   ├── ExtensionPath.php
│   │       │   ├── Filter.php
│   │       │   ├── FilterDescription.php
│   │       │   ├── FilterGroup.php
│   │       │   ├── FilterGroupDescription.php
│   │       │   ├── Gdpr.php
│   │       │   ├── Geo/
│   │       │   │   ├── City.php
│   │       │   │   ├── Country.php
│   │       │   │   └── Zone.php
│   │       │   ├── GeoZone.php
│   │       │   ├── Identifier.php
│   │       │   ├── Information.php
│   │       │   ├── InformationDescription.php
│   │       │   ├── InformationToLayout.php
│   │       │   ├── InformationToStore.php
│   │       │   ├── InjetarInterface.php
│   │       │   ├── Language.php
│   │       │   ├── Layout.php
│   │       │   ├── LayoutModule.php
│   │       │   ├── LayoutRoute.php
│   │       │   ├── LengthClass.php
│   │       │   ├── LengthClassDescription.php
│   │       │   ├── Location.php
│   │       │   ├── Manufacturer.php
│   │       │   ├── ManufacturerToLayout.php
│   │       │   ├── ManufacturerToStore.php
│   │       │   ├── Marketing.php
│   │       │   ├── MarketingReport.php
│   │       │   ├── Module.php
│   │       │   ├── Notification.php
│   │       │   ├── Option.php
│   │       │   ├── OptionDescription.php
│   │       │   ├── OptionValue.php
│   │       │   ├── OptionValueDescription.php
│   │       │   ├── Order.php
│   │       │   ├── OrderHistory.php
│   │       │   ├── OrderOption.php
│   │       │   ├── OrderProduct.php
│   │       │   ├── OrderReturn.php
│   │       │   ├── OrderStatus.php
│   │       │   ├── OrderSubscription.php
│   │       │   ├── OrderTotal.php
│   │       │   ├── Product.php
│   │       │   ├── ProductAttribute.php
│   │       │   ├── ProductCode.php
│   │       │   ├── ProductDescription.php
│   │       │   ├── ProductDiscount.php
│   │       │   ├── ProductFilter.php
│   │       │   ├── ProductImage.php
│   │       │   ├── ProductOption.php
│   │       │   ├── ProductOptionValue.php
│   │       │   ├── ProductRelated.php
│   │       │   ├── ProductReport.php
│   │       │   ├── ProductReward.php
│   │       │   ├── ProductSubscription.php
│   │       │   ├── ProductToCategory.php
│   │       │   ├── ProductToLayout.php
│   │       │   ├── ProductToStore.php
│   │       │   ├── ProductViewed.php
│   │       │   ├── ReturnAction.php
│   │       │   ├── ReturnHistory.php
│   │       │   ├── ReturnReason.php
│   │       │   ├── ReturnStatus.php
│   │       │   ├── Review.php
│   │       │   ├── SeoUrl.php
│   │       │   ├── Session.php
│   │       │   ├── Setting.php
│   │       │   ├── Startup.php
│   │       │   ├── Statistics.php
│   │       │   ├── StockStatus.php
│   │       │   ├── Store.php
│   │       │   ├── Subscription.php
│   │       │   ├── SubscriptionHistory.php
│   │       │   ├── SubscriptionLog.php
│   │       │   ├── SubscriptionOption.php
│   │       │   ├── SubscriptionPlan.php
│   │       │   ├── SubscriptionPlanDescription.php
│   │       │   ├── SubscriptionProduct.php
│   │       │   ├── SubscriptionStatus.php
│   │       │   ├── Supplier/
│   │       │   │   ├── Addresses.php
│   │       │   │   └── Supplier.php
│   │       │   ├── TaxClass.php
│   │       │   ├── TaxRate.php
│   │       │   ├── TaxRateToCustomerGroup.php
│   │       │   ├── TaxRule.php
│   │       │   ├── Theme.php
│   │       │   ├── Topic.php
│   │       │   ├── TopicDescription.php
│   │       │   ├── TopicToLayout.php
│   │       │   ├── TopicToStore.php
│   │       │   ├── Translation.php
│   │       │   ├── User.php
│   │       │   ├── UserAuthorize.php
│   │       │   ├── UserGroup.php
│   │       │   ├── UserLogin.php
│   │       │   ├── UserToken.php
│   │       │   ├── WeightClass.php
│   │       │   ├── WeightClassDescription.php
│   │       │   ├── ZoneDescription_deprecated.txt
│   │       │   ├── ZoneToGeoZone_deprecated.txt
│   │       │   ├── Zone_deprecated.txt
│   │       │   └── lista.txt
│   │       ├── Factory/
│   │       │   └── SimpleObjectFactory.php
│   │       ├── InterfaceEntity.php
│   │       ├── Observers/
│   │       │   ├── OrderEmailObserver.php
│   │       │   └── OrderObserverInterface.php
│   │       └── Repositories/
│   │           ├── AbstractRepository.php
│   │           ├── AddressFormatRepository.php
│   │           ├── AddressRepositoryDeprecated.txt
│   │           ├── ApiHistoryRepository.php
│   │           ├── ApiIpRepository.php
│   │           ├── ArticleRepository.php
│   │           ├── AttributeRepository.php
│   │           ├── BannerRepository.php
│   │           ├── BaseRepositoryInterface.php
│   │           ├── CartRepository.php
│   │           ├── CategoryRepository.php
│   │           ├── ConfigurationRepository.php
│   │           ├── CookieRepository.php
│   │           ├── CountryRepositoryDeprecated.txt
│   │           ├── CouponRepository.php
│   │           ├── CronRepository.php
│   │           ├── CurrencyRepository.php
│   │           ├── CustomerAddressesRepository.php
│   │           ├── CustomerAffiliateRepository.php
│   │           ├── CustomerAuthorizeRepository.php
│   │           ├── CustomerGroupRepository.php
│   │           ├── CustomerRepository.php
│   │           ├── CustomerRewardRepository.php
│   │           ├── CustomerTokenRepository.php
│   │           ├── CustomerTransactionRepository.php
│   │           ├── EventRepository.php
│   │           ├── ExtensionRepository.php
│   │           ├── FooterRepository.php
│   │           ├── GeoZoneRepository.php
│   │           ├── HeaderRepository.php
│   │           ├── HomeRepository.php
│   │           ├── InformationRepository.php
│   │           ├── LanguageRepository.php
│   │           ├── LayoutRepository.php
│   │           ├── LengthClassRepository.php
│   │           ├── MaintenanceRepository.php
│   │           ├── ManufacturerRepository.php
│   │           ├── OrderRepository.php
│   │           ├── OrderReturnRepository.php
│   │           ├── OrderStatusRepository.php
│   │           ├── PaginationRepository.php
│   │           ├── PriceRepository.php
│   │           ├── ProductDiscountRepository.php
│   │           ├── ProductImageRepository.php
│   │           ├── ProductOptionRepository.php
│   │           ├── ProductOptionValueRepository.php
│   │           ├── ProductRepository.php
│   │           ├── RepositoryFactory.php
│   │           ├── ReturnDictionaryRepository.php
│   │           ├── ReturnHistoryRepository.php
│   │           ├── SearchRepository.php
│   │           ├── SeoUrlRepository.php
│   │           ├── SessionRepository.php
│   │           ├── SettingRepository.php
│   │           ├── SitemapRepository.php
│   │           ├── StartupRepository.php
│   │           ├── StoreRepository.php
│   │           ├── SubscriptionRepository.php
│   │           ├── SubscriptionStatusRepository.php
│   │           ├── SupplierRepository.php
│   │           ├── TaxClassRepository.php
│   │           ├── TaxRateRepository.php
│   │           ├── TaxRuleRepository.php
│   │           ├── ThemeRepository.php
│   │           ├── TranslationRepository.php
│   │           ├── UserAuthorizeRepository.php
│   │           ├── UserGroupRepository.php
│   │           ├── UserLoginRepository.php
│   │           ├── UserRepository.php
│   │           ├── UserTokenRepository.php
│   │           ├── VoucherRepository.php
│   │           ├── WeightClassRepository.php
│   │           ├── WishlistRepository.php
│   │           └── ZoneRepositoryDeprecated.txt
│   ├── Services/
│   │   ├── Payments/
│   │   │   ├── Gateways/
│   │   │   │   ├── MercadoPagoAdapter.php
│   │   │   │   └── PayPalGateway.php
│   │   │   ├── PaymentGatewayFactory.php
│   │   │   ├── PaymentGatewayInterface.php
│   │   │   └── PaymentResult.php
│   │   └── Shipping/
│   │       ├── FlatRateShippingService.php
│   │       ├── FreeShippingService.php
│   │       └── WeightBasedShippingService.php
│   ├── Session/
│   │   └── AlphaSessionHandler.php
│   ├── Support/
│   │   ├── AlphaString.php
│   │   ├── Cache/
│   │   │   ├── CacheStrategyInterface.php
│   │   │   └── FilesystemCacheStrategy.php
│   │   ├── Collection.php
│   │   ├── Config.php
│   │   ├── Currency.php
│   │   ├── Customer.php
│   │   ├── Document.php
│   │   ├── EntityHydrator.php
│   │   ├── EvolutionGenerator.php
│   │   ├── Language.php
│   │   ├── LazyCollection.php
│   │   ├── Presenters/
│   │   │   └── ImagePresenter.php
│   │   ├── StoreSettings.php
│   │   ├── Tax.php
│   │   ├── Twig/
│   │   │   └── UrlExtension.php
│   │   ├── ViewHelper.php
│   │   └── Weight.php
│   ├── View/
│   │   ├── Errors/
│   │   │   └── 404.twig
│   │   └── ViewRenderer.php
│   └── language_legacy/
│       ├── en-gb/
│       │   ├── account/
│       │   │   ├── account.php
│       │   │   ├── address.php
│       │   │   ├── affiliate.php
│       │   │   ├── authorize.php
│       │   │   ├── edit.php
│       │   │   ├── forgotten.php
│       │   │   ├── login.php
│       │   │   ├── logout.php
│       │   │   ├── newsletter.php
│       │   │   ├── order.php
│       │   │   ├── password.php
│       │   │   ├── payment_method.php
│       │   │   ├── register.php
│       │   │   ├── returns.php
│       │   │   ├── reward.php
│       │   │   ├── subscription.php
│       │   │   ├── success.php
│       │   │   ├── tracking.php
│       │   │   ├── transaction.php
│       │   │   └── wishlist.php
│       │   ├── api/
│       │   │   ├── affiliate.php
│       │   │   ├── cart.php
│       │   │   ├── customer.php
│       │   │   ├── order.php
│       │   │   ├── payment_address.php
│       │   │   ├── payment_method.php
│       │   │   ├── shipping_address.php
│       │   │   ├── shipping_method.php
│       │   │   └── subscription.php
│       │   ├── checkout/
│       │   │   ├── cart.php
│       │   │   ├── checkout.php
│       │   │   ├── confirm.php
│       │   │   ├── failure.php
│       │   │   ├── payment_address.php
│       │   │   ├── payment_method.php
│       │   │   ├── register.php
│       │   │   ├── shipping_address.php
│       │   │   ├── shipping_method.php
│       │   │   └── success.php
│       │   ├── cms/
│       │   │   ├── blog.php
│       │   │   └── comment.php
│       │   ├── common/
│       │   │   ├── cart.php
│       │   │   ├── cookie.php
│       │   │   ├── currency.php
│       │   │   ├── footer.php
│       │   │   ├── header.php
│       │   │   ├── language.php
│       │   │   ├── maintenance.php
│       │   │   ├── menu.php
│       │   │   └── search.php
│       │   ├── cron/
│       │   │   ├── cron.php
│       │   │   └── subscription.php
│       │   ├── default.php
│       │   ├── en-gb.png
│       │   ├── error/
│       │   │   ├── not_found.php
│       │   │   └── permission.php
│       │   ├── information/
│       │   │   ├── contact.php
│       │   │   ├── gdpr.php
│       │   │   ├── gdpr_success.php
│       │   │   ├── information.php
│       │   │   └── sitemap.php
│       │   ├── mail/
│       │   │   ├── affiliate.php
│       │   │   ├── authorize.php
│       │   │   ├── authorize_reset.php
│       │   │   ├── forgotten.php
│       │   │   ├── gdpr.php
│       │   │   ├── gdpr_delete.php
│       │   │   ├── order_add.php
│       │   │   ├── order_alert.php
│       │   │   ├── order_edit.php
│       │   │   ├── register.php
│       │   │   ├── review.php
│       │   │   ├── subscription.php
│       │   │   ├── subscription_alert.php
│       │   │   └── transaction.php
│       │   ├── product/
│       │   │   ├── category.php
│       │   │   ├── compare.php
│       │   │   ├── manufacturer.php
│       │   │   ├── product.php
│       │   │   ├── related.php
│       │   │   ├── review.php
│       │   │   ├── search.php
│       │   │   ├── special.php
│       │   │   └── thumb.php
│       ├── fr-fr/
│       │   ├── account/
│       │   │   ├── account.php
│       │   │   ├── address.php
│       │   │   ├── affiliate.php
│       │   │   ├── authorize.php
│       │   │   ├── edit.php
│       │   │   ├── forgotten.php
│       │   │   ├── login.php
│       │   │   ├── logout.php
│       │   │   ├── newsletter.php
│       │   │   ├── order.php
│       │   │   ├── password.php
│       │   │   ├── payment_method.php
│       │   │   ├── register.php
│       │   │   ├── returns.php
│       │   │   ├── reward.php
│       │   │   ├── subscription.php
│       │   │   ├── success.php
│       │   │   ├── tracking.php
│       │   │   ├── transaction.php
│       │   │   └── wishlist.php
│       │   ├── api/
│       │   │   ├── affiliate.php
│       │   │   ├── cart.php
│       │   │   ├── customer.php
│       │   │   ├── order.php
│       │   │   ├── payment_address.php
│       │   │   ├── payment_method.php
│       │   │   ├── shipping_address.php
│       │   │   ├── shipping_method.php
│       │   │   └── subscription.php
│       │   ├── checkout/
│       │   │   ├── cart.php
│       │   │   ├── checkout.php
│       │   │   ├── confirm.php
│       │   │   ├── failure.php
│       │   │   ├── payment_address.php
│       │   │   ├── payment_method.php
│       │   │   ├── register.php
│       │   │   ├── shipping_address.php
│       │   │   ├── shipping_method.php
│       │   │   └── success.php
│       │   ├── cms/
│       │   │   ├── blog.php
│       │   │   └── comment.php
│       │   ├── common/
│       │   │   ├── cart.php
│       │   │   ├── cookie.php
│       │   │   ├── currency.php
│       │   │   ├── footer.php
│       │   │   ├── header.php
│       │   │   ├── language.php
│       │   │   ├── maintenance.php
│       │   │   ├── menu.php
│       │   │   └── search.php
│       │   ├── cron/
│       │   │   ├── cron.php
│       │   │   └── subscription.php
│       │   ├── default.php
│       │   ├── error/
│       │   │   ├── not_found.php
│       │   │   └── permission.php
│       │   ├── fr-fr.png
│       │   ├── information/
│       │   │   ├── contact.php
│       │   │   ├── gdpr.php
│       │   │   ├── gdpr_success.php
│       │   │   ├── information.php
│       │   │   └── sitemap.php
│       │   ├── mail/
│       │   │   ├── affiliate.php
│       │   │   ├── authorize.php
│       │   │   ├── authorize_reset.php
│       │   │   ├── forgotten.php
│       │   │   ├── gdpr.php
│       │   │   ├── gdpr_delete.php
│       │   │   ├── order_add.php
│       │   │   ├── order_alert.php
│       │   │   ├── order_edit.php
│       │   │   ├── register.php
│       │   │   ├── review.php
│       │   │   ├── subscription.php
│       │   │   ├── subscription_alert.php
│       │   │   └── transaction.php
│       │   ├── product/
│       │   │   ├── category.php
│       │   │   ├── compare.php
│       │   │   ├── manufacturer.php
│       │   │   ├── product.php
│       │   │   ├── related.php
│       │   │   ├── review.php
│       │   │   ├── search.php
│       │   │   ├── special.php
│       │   │   └── thumb.php
│       └── pt-br/
│           ├── account/
│           │   ├── account.php
│           │   ├── address.php
│           │   ├── affiliate.php
│           │   ├── edit.php
│           │   ├── forgotten.php
│           │   ├── login.php
│           │   ├── logout.php
│           │   ├── newsletter.php
│           │   ├── order.php
│           │   ├── password.php
│           │   ├── payment_method.php
│           │   ├── recurring.php
│           │   ├── register.php
│           │   ├── reset.php
│           │   ├── returns.php
│           │   ├── reward.php
│           │   ├── success.php
│           │   ├── tracking.php
│           │   ├── transaction.php
│           │   ├── voucher.php
│           │   └── wishlist.php
│           ├── affiliate/
│           │   ├── login.php
│           │   ├── register.php
│           │   └── success.php
│           ├── api/
│           │   ├── cart.php
│           │   ├── coupon.php
│           │   ├── currency.php
│           │   ├── customer.php
│           │   ├── login.php
│           │   ├── order.php
│           │   ├── payment.php
│           │   ├── reward.php
│           │   ├── shipping.php
│           │   └── voucher.php
│           ├── checkout/
│           │   ├── cart.php
│           │   ├── checkout.php
│           │   ├── failure.php
│           │   ├── payment_address.php
│           │   ├── payment_method.php
│           │   ├── register.php
│           │   ├── shipping_address.php
│           │   ├── shipping_method.php
│           │   └── success.php
│           ├── common/
│           │   ├── cart.php
│           │   ├── cookie.php
│           │   ├── currency.php
│           │   ├── footer.php
│           │   ├── header.php
│           │   ├── home.php
│           │   ├── language.php
│           │   ├── maintenance.php
│           │   ├── menu.php
│           │   └── search.php
│           ├── default.php
│           ├── error/
│           │   └── not_found.php
│           ├── extension/
│           │   ├── captcha/
│           │   │   ├── basic.php
│           │   │   └── google.php
│           │   ├── credit_card/
│           │   │   ├── sagepay_direct.php
│           │   │   ├── sagepay_server.php
│           │   │   └── squareup.php
│           │   ├── module/
│           │   │   ├── account.php
│           │   │   ├── amazon_login.php
│           │   │   ├── amazon_pay.php
│           │   │   ├── bestseller.php
│           │   │   ├── category.php
│           │   │   ├── divido_calculator.php
│           │   │   ├── ebay_listing.php
│           │   │   ├── featured.php
│           │   │   ├── filter.php
│           │   │   ├── google_hangouts.php
│           │   │   ├── information.php
│           │   │   ├── latest.php
│           │   │   ├── laybuy_layout.php
│           │   │   ├── special.php
│           │   │   └── store.php
│           │   ├── openbay/
│           │   │   ├── amazon_order.php
│           │   │   ├── amazonus_order.php
│           │   │   ├── ebay_order.php
│           │   │   └── etsy_order.php
│           │   ├── payment/
│           │   │   ├── alipay.php
│           │   │   ├── alipay_cross.php
│           │   │   ├── amazon_login_pay.php
│           │   │   ├── authorizenet_aim.php
│           │   │   ├── authorizenet_sim.php
│           │   │   ├── bank_transfer.php
│           │   │   ├── bluepay_hosted.php
│           │   │   ├── bluepay_redirect.php
│           │   │   ├── cardconnect.php
│           │   │   ├── cardinity.php
│           │   │   ├── cheque.php
│           │   │   ├── cod.php
│           │   │   ├── divido.php
│           │   │   ├── eway.php
│           │   │   ├── firstdata.php
│           │   │   ├── firstdata_remote.php
│           │   │   ├── free_checkout.php
│           │   │   ├── g2apay.php
│           │   │   ├── globalpay.php
│           │   │   ├── globalpay_remote.php
│           │   │   ├── klarna_account.php
│           │   │   ├── klarna_checkout.php
│           │   │   ├── klarna_invoice.php
│           │   │   ├── laybuy.php
│           │   │   ├── liqpay.php
│           │   │   ├── nochex.php
│           │   │   ├── paymate.php
│           │   │   ├── paypoint.php
│           │   │   ├── payza.php
│           │   │   ├── perpetual_payments.php
│           │   │   ├── pilibaba.php
│           │   │   ├── pp_braintree.php
│           │   │   ├── pp_express.php
│           │   │   ├── pp_payflow.php
│           │   │   ├── pp_payflow_iframe.php
│           │   │   ├── pp_pro.php
│           │   │   ├── pp_pro_iframe.php
│           │   │   ├── pp_standard.php
│           │   │   ├── realex.php
│           │   │   ├── realex_remote.php
│           │   │   ├── sagepay_direct.php
│           │   │   ├── sagepay_server.php
│           │   │   ├── sagepay_us.php
│           │   │   ├── securetrading_pp.php
│           │   │   ├── securetrading_ws.php
│           │   │   ├── skrill.php
│           │   │   ├── squareup.php
│           │   │   ├── twocheckout.php
│           │   │   ├── web_payment_software.php
│           │   │   └── worldpay.php
│           │   ├── recurring/
│           │   │   ├── pp_express.php
│           │   │   └── squareup.php
│           │   ├── shipping/
│           │   │   ├── auspost.php
│           │   │   ├── citylink.php
│           │   │   ├── ec_ship.php
│           │   │   ├── fedex.php
│           │   │   ├── flat.php
│           │   │   ├── free.php
│           │   │   ├── item.php
│           │   │   ├── parcelforce_48.php
│           │   │   ├── pickup.php
│           │   │   ├── pilibaba.php
│           │   │   ├── royal_mail.php
│           │   │   ├── ups.php
│           │   │   ├── usps.php
│           │   │   └── weight.php
│           │   └── total/
│           │       ├── coupon.php
│           │       ├── credit.php
│           │       ├── handling.php
│           │       ├── klarna_fee.php
│           │       ├── low_order_fee.php
│           │       ├── reward.php
│           │       ├── shipping.php
│           │       ├── sub_total.php
│           │       ├── total.php
│           │       └── voucher.php
│           ├── information/
│           │   ├── contact.php
│           │   ├── information.php
│           │   ├── sitemap.php
│           │   └── tracking.php
│           ├── mail/
│           │   ├── affiliate.php
│           │   ├── forgotten.php
│           │   ├── order_add.php
│           │   ├── order_alert.php
│           │   ├── order_edit.php
│           │   ├── register.php
│           │   ├── review.php
│           │   ├── transaction.php
│           │   └── voucher.php
│           ├── product/
│           │   ├── category.php
│           │   ├── compare.php
│           │   ├── manufacturer.php
│           │   ├── product.php
│           │   ├── search.php
│           │   └── special.php
│           ├── pt-br.php
│           └── pt-br.png
├── data_base_new_schema/
│   ├── db_schema.php
│   ├── new_suppliers_insert_query.sql
│   ├── new_suppliers_select_query.sql
│   └── new_suppliers_table.sql
├── diagrams/
│   ├── diagrama_de_arquitetura.mmd
│   ├── diagrama_de_arquitetura0.mmd
│   ├── diagrama_de_pastas_so-pastas.puml
│   ├── estrutura.puml
│   ├── info_entrega.md
│   ├── pastas_estrutura.puml
│   └── termos.md
├── docs/
│   ├── ALPHA_ENGINE_ARCHITECTURE.md
│   ├── README1.md
│   ├── README4.md
│   ├── anti_patterns.md
│   ├── auth_progress.md
│   ├── cart_progress.md
│   ├── catalog_progress.md
│   ├── directories_structure.md
│   ├── pks_fks_bigint_feasibility.md
│   ├── session_decoupling_analysis.md
│   └── styles.md
├── error.html
├── lib/
│   ├── libncurses.so.5
│   └── libtinfo.so.5
├── php.ini
├── public_html/
│   ├── .htaccess
│   ├── LPDHED2dC7Gjrg2b/
│   │   ├── .htaccess
│   │   └── index.php
│   ├── css/
│   │   ├── admin/
│   │   │   ├── admin.css
│   │   │   ├── components.css
│   │   │   ├── layout.css
│   │   │   └── variables.css
│   │   ├── app.css
│   │   ├── assets/
│   │   │   └── css/
│   │   └── custom/
│   │       ├── new-stylesheet.css
│   │       └── personalizada.css
│   ├── favicon.ico
│   ├── fonts/
│   │   └── fontawesome/
│   │       ├── LICENSE.txt
│   │       ├── css/
│   │       │   ├── all.css
│   │       │   ├── all.min.css
│   │       │   ├── brands.css
│   │       │   ├── brands.min.css
│   │       │   ├── fontawesome.css
│   │       │   ├── fontawesome.min.css
│   │       │   ├── regular.css
│   │       │   ├── regular.min.css
│   │       │   ├── solid.css
│   │       │   ├── solid.min.css
│   │       │   ├── svg-with-js.css
│   │       │   ├── svg-with-js.min.css
│   │       │   ├── v4-font-face.css
│   │       │   ├── v4-font-face.min.css
│   │       │   ├── v4-shims.css
│   │       │   ├── v4-shims.min.css
│   │       │   ├── v5-font-face.css
│   │       │   └── v5-font-face.min.css
│   │       └── webfonts/
│   │           ├── fa-brands-400.ttf
│   │           ├── fa-brands-400.woff2
│   │           ├── fa-regular-400.ttf
│   │           ├── fa-regular-400.woff2
│   │           ├── fa-solid-900.ttf
│   │           ├── fa-solid-900.woff2
│   │           ├── fa-v4compatibility.ttf
│   │           └── fa-v4compatibility.woff2
│   ├── image/
│   │   ├── banners/
│   │   │   ├── banner_01_argamassa_e_rejuntes_quartzolit.png.webp
│   │   │   ├── banner_05_argamassa_e_rejuntes_quartzolit.png.webp
│   │   │   ├── banner_08_argamassa_e_rejuntes_quartzolit.png.webp
│   │   │   ├── cart.png
│   │   │   ├── logo.png
│   │   │   └── logo2.png
│   │   ├── category/
│   │   │   └── category_1780677063_6a22f9c73f29c.png
│   │   ├── logo.png
│   │   ├── logo2.png
│   │   ├── logomarcas/
│   │   │   ├── Companhia_Siderúrgica_Nacional.png
│   │   │   ├── Krona-logo-2.png
│   │   │   ├── Logo-Ceramica-LaranjaL.png
│   │   │   ├── Logo-MGM.png
│   │   │   ├── Logo-Mebuki.png
│   │   │   ├── alianca-logo.png
│   │   │   ├── alumstar.png
│   │   │   ├── arames-brasil.jpg
│   │   │   ├── astra-logo-1.gif
│   │   │   ├── astra-logo-2.gif
│   │   │   ├── blukit-logo.png
│   │   │   ├── botinas-guerreiro-2.png
│   │   │   ├── botinas-guerreiro-logo-2.png
│   │   │   ├── botinas-guerreiro-logo.png
│   │   │   ├── brasilit-logo.png
│   │   │   ├── brukit-logo.svg
│   │   │   ├── carmelo-fior-logo.png
│   │   │   ├── ceramica-almeida-logo-2.png
│   │   │   ├── ceramica-almeida-logo.png
│   │   │   ├── ceramica-nardini-logo.svg
│   │   │   ├── ceramica-nova-firenze-logo.png
│   │   │   ├── condifios-logo.png
│   │   │   ├── cortag-logo-2.svg
│   │   │   ├── cortag-logo.svg
│   │   │   ├── d-aco.png
│   │   │   ├── fame-logo.png
│   │   │   ├── formigres-logo (2).png
│   │   │   ├── formigres-logo-2.png
│   │   │   ├── fortlev-logo.png
│   │   │   ├── gerdal-logo.png
│   │   │   ├── gmic.svg
│   │   │   ├── godmix-logo.png
│   │   │   ├── grupo-almeida-logo.png
│   │   │   ├── grupo-baumgart-logo.png
│   │   │   ├── grupo-rocha-logo.png
│   │   │   ├── hervy-logo.png
│   │   │   ├── incopisos-logo.png
│   │   │   ├── infibra-logo-2.png
│   │   │   ├── infibra-logo.png
│   │   │   ├── inovax-logo.png
│   │   │   ├── iraja-logo.jpg
│   │   │   ├── jetmix-logo.png
│   │   │   ├── kadesh.png
│   │   │   ├── kapazi-logo.svg
│   │   │   ├── krona-logo.png
│   │   │   ├── lista-logo.txt
│   │   │   ├── logo-3f.png
│   │   │   ├── logo-Canal-260x65.jpg
│   │   │   ├── logo-Grupo-Ceral.png
│   │   │   ├── logo-ISOMARMORE.png
│   │   │   ├── logo-Indusfios.jpg
│   │   │   ├── logo-Lucheti.png
│   │   │   ├── logo-Lukscolor.png
│   │   │   ├── logo-Nardini.svg
│   │   │   ├── logo-Portas_Meu_Lar.png
│   │   │   ├── logo-RW-Pias.gif
│   │   │   ├── logo-Rodan.png
│   │   │   ├── logo-acofer.jpg
│   │   │   ├── logo-cozimax.svg
│   │   │   ├── logo-i9.png
│   │   │   ├── logo-itapex.jpg
│   │   │   ├── logo-japi.png
│   │   │   ├── logo-king-fer.png
│   │   │   ├── logo-metalflex.png
│   │   │   ├── logo-metalurgia-rocha.png
│   │   │   ├── logo-pinceis-roma.svg
│   │   │   ├── logo-ponteiras-brec.png
│   │   │   ├── logo-roloflex.png
│   │   │   ├── logo-rorato-1.png
│   │   │   ├── logo-sampaflex.png
│   │   │   ├── logo_AKATO.png
│   │   │   ├── logo_Lider.png
│   │   │   ├── logo_ceramica-martins.png
│   │   │   ├── logo_nova_santamarina.png
│   │   │   ├── lorenzetti-logo.jpg
│   │   │   ├── luksnova-logo.png
│   │   │   ├── megatron-logo.png
│   │   │   ├── multilit-logo.png
│   │   │   ├── paupedras-logo.jpg
│   │   │   ├── quartzolit-logo.png
│   │   │   ├── radial-2.png
│   │   │   ├── radial-logo.png
│   │   │   ├── saint-gobain-logo.svg
│   │   │   ├── saint-gobain-marcas-logo.png
│   │   │   ├── sherwin-williams-logo.jpg
│   │   │   ├── sherwin-williams-logo.png
│   │   │   ├── stam-logo.svg
│   │   │   ├── thermoplast-logo.png
│   │   │   ├── tigre-logo.png
│   │   │   ├── tintas-iraja-logo.png
│   │   │   ├── vedacit-logo.png
│   │   │   ├── viapol-logo.gif
│   │   │   ├── votorantim-logo.svg
│   │   │   └── wurth-logo.png
│   │   ├── logomark/
│   │   │   ├── logo.png
│   │   │   └── logo2.png
│   │   ├── manufacturer/
│   │   │   ├── manufacturer_1780667716_6a22d54452292.jpg
│   │   │   └── manufacturer_1780669698_6a22dd02b97fc.gif
│   │   ├── no-image.png
│   │   ├── product/
│   │   │   ├── index.html
│   │   │   ├── product_2919_1780661646.jpg
│   │   │   ├── product_2919_1780662262.jpg
│   │   │   └── product_2919_1780662492.jpg
│   │   └── seamless/
│   │       ├── Roof01.jpg
│   │       ├── Roof02.jpg
│   │       ├── Stucco4.jpg
│   │       ├── index.html
│   │       └── scandinavian-roof-tile-seamless.jpg
│   ├── img/
│   │   └── product/
│   │       ├── product_2919_1780661646.jpg
│   │       ├── product_2919_1780662262.jpg
│   │       └── product_2919_1780662492.jpg
│   ├── index.php
│   ├── index_unit_test.php
│   └── js/
│       ├── app.js
│       ├── cart/
│       │   ├── cart.js
│       │   └── checkout.js
│       └── custom/
│           ├── automatic-address.js
│           ├── form-validator.js
│           └── shipping-simulator.js
├── resources/
│   └── views/
│       ├── admin/
│       │   ├── auth/
│       │   │   ├── error.html.twig
│       │   │   ├── forgot_password.html.twig
│       │   │   ├── login.html.twig
│       │   │   ├── reset_password.html.twig
│       │   │   └── setup.html.twig
│       │   ├── catalog/
│       │   │   ├── manufacturer/
│       │   │   │   ├── create.html.twig
│       │   │   │   ├── edit.html.twig
│       │   │   │   └── index.html.twig
│       │   │   └── supplier/
│       │   │       ├── create.html.twig
│       │   │       ├── edit.html.twig
│       │   │       └── index.html.twig
│       │   ├── components/
│       │   │   └── organisms/
│       │   │       └── topbar.html.twig
│       │   ├── customer/
│       │   │   ├── Address/
│       │   │   │   ├── create.html.twig
│       │   │   │   └── edit.html.twig
│       │   │   └── customer/
│       │   │       ├── _form.html.twig
│       │   │       ├── create.html.twig
│       │   │       ├── edit.html.twig
│       │   │       ├── index.html.twig
│       │   │       └── show.html.twig
│       │   ├── layouts/
│       │   │   ├── base.html.twig
│       │   │   └── base_auth.html.twig
│       │   ├── macros/
│       │   │   └── forms.html.twig
│       │   ├── order/
│       │   ├── pages/
│       │   │   ├── category/
│       │   │   │   ├── create.html.twig
│       │   │   │   ├── edit.html.twig
│       │   │   │   └── list.html.twig
│       │   │   ├── dashboard/
│       │   │   │   └── index.html.twig
│       │   │   ├── errors/
│       │   │   │   └── 403.html.twig
│       │   │   └── products/
│       │   │       ├── _form.html.twig
│       │   │       ├── create.html.twig
│       │   │       ├── edit.html.twig
│       │   │       └── list.html.twig
│       │   ├── sales/
│       │   │   └── order/
│       │   │       ├── index.html.twig
│       │   │       ├── invoice.html.twig
│       │   │       └── show.html.twig
│       │   └── setting/
│       │       └── store_setting/
│       │           └── edit.html.twig
│       ├── base.html.twig
│       ├── components/
│       │   ├── atoms/
│       │   │   ├── button.twig
│       │   │   ├── link.twig
│       │   │   ├── logo.twig
│       │   │   ├── menu-button.twig
│       │   │   └── nav-link.twig
│       │   ├── molecules/
│       │   │   ├── alert.twig
│       │   │   ├── breadcrumbs.twig
│       │   │   ├── card-register.twig
│       │   │   ├── card-user.twig
│       │   │   ├── dropdown-recursive.twig
│       │   │   ├── footer-column.twig
│       │   │   ├── form-group-password.twig
│       │   │   ├── form-group.twig
│       │   │   ├── nav-menu.twig
│       │   │   ├── pagination.html.twig
│       │   │   ├── top-nav.twig
│       │   │   └── utility-bar.twig
│       │   └── organisms/
│       │       ├── aside_filters.html.twig
│       │       ├── department-menu.twig
│       │       ├── footer.twig
│       │       ├── form-login.twig
│       │       └── header.twig
│       ├── home.html.twig
│       ├── layouts/
│       │   └── base.html.twig
│       └── pages/
│           ├── auth/
│           │   ├── request-password-reset.html.twig
│           │   └── reset-password.html.twig
│           ├── cart/
│           │   ├── cart.twig
│           │   ├── checkout.twig
│           │   ├── payment_method.twig
│           │   ├── shipping-address.twig
│           │   └── success.twig
│           ├── category/
│           │   ├── category-card.html.twig
│           │   └── show.html.twig
│           ├── errors/
│           │   └── 404.html.twig
│           ├── information/
│           │   ├── contact.twig
│           │   ├── show.html.twig
│           │   └── sitemap.twig
│           ├── product/
│           │   ├── product-card.html.twig
│           │   ├── product-returns.html.twig
│           │   ├── search.html.twig
│           │   └── show.html.twig
│           └── users/
│               ├── accounts/
│               │   ├── Transactions.html.twig
│               │   ├── account.twig
│               │   ├── newsletter.twig
│               │   ├── order-history.twig
│               │   ├── orders.twig
│               │   ├── update-account.html.twig
│               │   └── wishlist.twig
│               ├── addresses/
│               │   ├── create.twig
│               │   ├── edit.twig
│               │   └── index.twig
│               ├── edit.html.twig
│               ├── index.html.twig
│               ├── login.twig
│               ├── nota_20260606_133933.md
│               ├── nota_20260606_134015.md
│               ├── register.twig
│               └── return.twig
├── robots.txt
└── tests/
    ├── TestLogging.php
    ├── TestOOBE.php
    ├── TestOrderStatus1.php
    ├── scripts_uteis/
    │   ├── Gerador-automático-de-documentação-de-pastas.php
    │   ├── Gerador-automático-de-documentação_apenas-pastas_.php
    │   ├── NovoEnderecamento/
    │   │   ├── Como_ler_e_validar_esses_dados_no_seu_código.php
    │   │   ├── CondadosSuecia.sql
    │   │   ├── TodosEstadosBrasileiros.sql
    │   │   ├── ValidaBloqueioNoCheckout.php
    │   │   ├── consulta_cidade_pais_code.sql
    │   │   ├── create-tables.sql
    │   │   ├── create_address_supplies.sql
    │   │   ├── insert_city
    │   │   ├── insert_country.sql
    │   │   └── query_de_consulta_supplier.sql
    │   ├── Pyton/
    │   │   └── scratch_analyze.py
    │   ├── SearchTest.php
    │   ├── TestPrivileges.php
    │   ├── converter_tipos_das_PKs_e_FKs.sql
    │   ├── php-bd/
    │   │   ├── AtualizarImage.php
    │   │   └── DB-Search.php
    │   ├── substitui_store_zero_store_um.php
    │   ├── test_customer_registration.php
    │   └── verifica-se-o-namespace-coincidem-com-a-classe.php
    ├── test_customer_addresses.php
    ├── test_order_addresses.php
    └── test_translation_loading.php
@endfiles
